// Shared theme definitions for all ServicesLocal apps
// (serviceslocalchat, serviceslocalemail, serviceslocalwhatsapp).
// Edit ONCE here — all three apps pick up the change automatically.

export const POLLINATIONS_BASE = 'https://image.pollinations.ai/prompt/'

export function serviceImg(prompt) {
  return POLLINATIONS_BASE + encodeURIComponent(prompt + ', professional service photography, dark moody background, cinematic lighting, 4k') + '?width=480&height=854&nologo=true&seed=42'
}

export const FOOD_TYPES = {
  'Nasi': ['Nasi Goreng', 'Nasi Uduk', 'Nasi Kuning', 'Nasi Padang', 'Nasi Campur', 'Nasi Kucing', 'Nasi Bakar', 'Nasi Pecel', 'Nasi Liwet', 'Lontong Sayur', 'Ketupat Sayur'],
  'Mie': ['Mie Goreng', 'Mie Rebus', 'Mie Ayam', 'Bakmi Jawa', 'Mie Tek-Tek', 'Kwetiau Goreng', 'Bihun Goreng', 'Mie Aceh'],
  'Sop/Soto': ['Soto Ayam', 'Soto Betawi', 'Soto Lamongan', 'Soto Madura', 'Bakso', 'Bakso Urat', 'Rawon', 'Tongseng', 'Sop Iga', 'Sop Buntut'],
  'Sate/Bakar': ['Sate Ayam', 'Sate Kambing', 'Sate Padang', 'Sate Madura', 'Sate Taichan', 'Sate Usus', 'Jagung Bakar', 'Ikan Bakar', 'Ayam Bakar'],
  'Gorengan': ['Bakwan', 'Tahu Goreng', 'Tempe Goreng', 'Tahu Isi', 'Pisang Goreng', 'Ubi Goreng', 'Risoles', 'Cireng', 'Comro', 'Martabak Telur'],
  'Jajanan': ['Siomay', 'Batagor', 'Pempek', 'Cilok', 'Cimol', 'Tahu Bulat', 'Lumpia', 'Seblak', 'Telur Gulung', 'Sempol Ayam', 'Sosis Bakar'],
  'Ayam': ['Ayam Goreng', 'Ayam Bakar', 'Ayam Penyet', 'Ayam Geprek', 'Ayam Kremes', 'Ayam Rica-Rica', 'Pecel Lele'],
  'Seafood': ['Ikan Bakar', 'Ikan Goreng', 'Udang Bakar', 'Cumi Goreng', 'Kerang Rebus', 'Gurame Goreng'],
  'Roti': ['Roti Bakar', 'Martabak Manis', 'Roti Canai', 'Pukis', 'Kue Cubit', 'Kue Pancong'],
  'Minuman': ['Es Teh Manis', 'Es Jeruk', 'Es Kelapa', 'Es Cendol', 'Es Campur', 'Es Cincau', 'Es Teler', 'Jus Alpukat', 'Jus Mangga', 'Wedang Jahe', 'Bandrek', 'Sekoteng', 'Es Buah'],
  'Dessert': ['Klepon', 'Onde-Onde', 'Lupis', 'Dadar Gulung', 'Serabi', 'Kue Putu', 'Kue Lapis', 'Getuk', 'Wingko'],
  'Bubur': ['Bubur Ayam', 'Bubur Kacang Hijau', 'Bubur Sumsum', 'Bubur Ketan Hitam', 'Bubur Manado'],
}

export const THEME_PRESETS = [
  // Home services
  { id: 'cleaning', accent: '#3498DB', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_01_01%20PM.png', label: '#1 Cleaning', category: 'Cleaning', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU'], foodTypes: ['Cleaning', 'House Cleaning', 'Office Cleaning'], variants: [serviceImg('professional house cleaning service workers in uniform with mop and vacuum')] },
  { id: 'plumbing', accent: '#1B6BA8', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2002_35_55%20PM.png', label: '#2 Plumbing', category: 'Plumbing', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU', 'DE'], foodTypes: ['Plumbing', 'Pipes', 'Bathroom Repair'], variants: [serviceImg('plumber fixing pipes under sink with tools')] },
  { id: 'electrician', accent: '#F1C40F', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_02_13%20PM.png', label: '#3 Electrician', category: 'Electrician', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'US', 'GB', 'AU', 'DE'], foodTypes: ['Electrician', 'Wiring', 'Electrical'], variants: [serviceImg('electrician working on wires panel with tools')] },
  { id: 'aircon', accent: '#3498DB', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2002_28_18%20PM.png', label: '#4 AC Service', category: 'AC Service', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU'], foodTypes: ['AC Service', 'Air Conditioning', 'AC Repair'], variants: [serviceImg('air conditioner technician installing AC unit on wall')] },
  { id: 'carpenter', accent: '#8B4513', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2002_43_27%20PM.png', label: '#5 Carpenter', category: 'Carpenter', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Carpenter', 'Tukang Kayu', 'Woodwork'], variants: [serviceImg('carpenter working with wood saws and tools workshop')] },
  { id: 'painter', accent: '#2ECC71', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_14_14%20PM.png', label: '#6 Painter', category: 'Painter', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Painter', 'Wall Painting', 'House Painting'], variants: [serviceImg('house painter painting wall with roller brush')] },
  { id: 'gardening', accent: '#27AE60', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_36_46%20PM.png', label: '#7 Gardening', category: 'Gardening', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Gardening', 'Tukang Kebun', 'Landscaping'], variants: [serviceImg('gardener trimming hedges with shears in garden')] },
  { id: 'locksmith', accent: '#7F8C8D', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_33_08%20PM.png', label: '#8 Locksmith', category: 'Locksmith', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Locksmith', 'Key Service', 'Lock Repair'], variants: [serviceImg('locksmith working on door lock with tools and keys')] },
  { id: 'pest', accent: '#1ABC9C', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_29_27%20PM.png', label: '#9 Pest Control', category: 'Pest Control', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Pest Control', 'Exterminator', 'Insect Control'], variants: ['https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_29_54%20PM.png', serviceImg('pest control technician spraying outdoor with equipment')] },
  // Beauty + wellness
  { id: 'massage', accent: '#E91E63', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2012_58_52%20PM.png', label: '#10 Massage', category: 'Massage', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU'], foodTypes: ['Massage', 'Pijat', 'Spa', 'Therapy'], variants: ['https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2012_59_47%20PM.png', serviceImg('massage therapist hands on back relaxing spa setting')] },
  { id: 'salon', accent: '#FF69B4', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_30_07%20PM.png', label: '#11 Salon', category: 'Salon', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU'], foodTypes: ['Salon', 'Hair', 'Beauty'], variants: [serviceImg('hair salon stylist cutting hair beauty service')] },
  { id: 'beautician', isNew: true, accent: '#BE185D', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2012_57_31%20PM.png', label: '#11b Beautician', category: 'Beautician', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU'], foodTypes: ['Beautician', 'Facial', 'Makeup Artist', 'Eyebrow', 'Eyelash'] },
  { id: 'laser', isNew: true, accent: '#8E44AD', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_03_33%20PM.png', label: '#11c Laser Service', category: 'Laser Service', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU', 'KR', 'JP'], foodTypes: ['Laser Service', 'Laser Hair Removal', 'Aesthetic', 'Skin Treatment'] },
  { id: 'tattoo', accent: '#1a1a1a', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_33_08%20PM.png', label: '#12 Tattoo', category: 'Tattoo', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU', 'DE'], foodTypes: ['Tattoo', 'Tattoo Studio', 'Body Art'], variants: [serviceImg('tattoo artist working on client arm tattoo studio')] },
  { id: 'yoga', accent: '#8E44AD', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_37_27%20PM.png', label: '#13 Yoga Trainer', category: 'Yoga Trainer', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Yoga', 'Fitness', 'Personal Trainer', 'Yoga Trainer'], variants: [serviceImg('yoga instructor in studio leading class fitness')] },
  // Automotive
  { id: 'mechanic', accent: '#dc2626', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_40_27%20PM.png', label: '#14 Mechanic', category: 'Mechanic', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU'], foodTypes: ['Mechanic', 'Bengkel', 'Auto Repair', 'Car Service'], variants: [serviceImg('auto mechanic working on car engine in garage')] },
  { id: 'carwash', accent: '#2980B9', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2012_54_50%20PM.png', label: '#15 Car Wash', category: 'Car Wash', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Car Wash', 'Auto Detailing', 'Car Care'], variants: [serviceImg('car wash detailing service spraying soap on vehicle')] },
  { id: 'driving', accent: '#FFD600', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2007_52_03%20PM.png', label: '#16 Driving Instructor', category: 'Driving Instructor', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Driving Instructor', 'Driving School', 'Driving Lessons'], variants: [serviceImg('driving instructor in car teaching student to drive')] },
  // Tailored services
  { id: 'photographer', accent: '#1a1a1a', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_41_08%20PM.png', label: '#17 Photographer', category: 'Photographer', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU'], foodTypes: ['Photographer', 'Wedding Photography', 'Photo Studio'], variants: [serviceImg('professional photographer with camera and studio lighting')] },
  { id: 'tailor', isNew: true, accent: '#8E44AD', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2003_05_15%20AM.png', label: '#18 Tailor', category: 'Tailor', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB'], foodTypes: ['Tailor', 'Penjahit', 'Sewing', 'Alterations'], variants: [serviceImg('tailor sewing clothes with sewing machine in workshop')] },
  { id: 'petgroom', accent: '#F39C12', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2002_25_24%20PM.png?updatedAt=1778484338757', label: '#19 Pet Grooming', category: 'Pet Grooming', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Pet Grooming', 'Dog Grooming', 'Pet Care'], variants: [serviceImg('professional pet groomer washing dog grooming salon')] },
  // Education + professional
  { id: 'tutor', accent: '#9B59B6', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_05_18%20PM.png', label: '#20 Tutor', category: 'Tutor', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB'], foodTypes: ['Tutor', 'Les Privat', 'Tutoring', 'Education'], variants: ['https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_04_52%20PM.png', serviceImg('private tutor teaching student at desk with books')] },
  { id: 'music', accent: '#E74C3C', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2007_52_31%20PM.png', label: '#21 Music Lessons', category: 'Music Lessons', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Music Lessons', 'Piano', 'Guitar', 'Music Teacher'], variants: [serviceImg('music teacher giving piano lesson student playing')] },
  { id: 'webdev', accent: '#3498DB', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2007_53_16%20PM.png', label: '#22 Web Developer', category: 'Web Developer', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU', 'DE'], foodTypes: ['Web Developer', 'Freelance', 'IT Service', 'Programming'], variants: [serviceImg('web developer freelancer coding on laptop dual monitor setup')] },
  { id: 'translator', accent: '#16A085', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2007_53_39%20PM.png', label: '#23 Translator', category: 'Translator', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'US', 'GB', 'DE', 'FR'], foodTypes: ['Translator', 'Translation', 'Interpreter'], variants: [serviceImg('professional translator working with multilingual documents headset')] },
  { id: 'accountant', accent: '#34495E', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2007_54_03%20PM.png', label: '#24 Accountant', category: 'Accountant', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Accountant', 'Bookkeeping', 'Tax', 'Akuntan'], variants: [serviceImg('accountant working with calculator and financial documents')] },
  { id: 'lawyer', accent: '#2C3E50', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2007_54_31%20PM.png', label: '#25 Lawyer', category: 'Lawyer', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Lawyer', 'Legal Service', 'Notary', 'Pengacara'], variants: [serviceImg('professional lawyer office with books law firm')] },
  // Events + care
  { id: 'event', accent: '#E91E63', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2008_12_01%20PM.png', label: '#26 Event Planning', category: 'Event Planning', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Event Planning', 'Wedding', 'Catering'], variants: [serviceImg('event planner organizing wedding reception elegant setup')] },
  { id: 'childcare', accent: '#FF69B4', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2008_02_00%20PM.png', label: '#27 Childcare', category: 'Childcare', countries: ['ID', 'MY', 'SG', 'TH', 'US', 'GB', 'AU'], foodTypes: ['Childcare', 'Babysitter', 'Nanny', 'Pengasuh Anak'], variants: [serviceImg('childcare worker playing with happy children daycare')] },
  { id: 'courier', accent: '#FF6B35', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2007_55_04%20PM.png', label: '#28 Courier', category: 'Courier', countries: ['ID', 'MY', 'SG', 'TH', 'VN', 'PH', 'US', 'GB', 'AU'], foodTypes: ['Courier', 'Delivery', 'Kurir', 'Package Delivery'], variants: [serviceImg('motorcycle courier delivering package urban street')] },
  { id: 'leather', isNew: true, accent: '#5D2E0D', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_11_10%20PM.png', label: '#29 Leather Supplier', category: 'Leather Supplier', countries: ['ID','MY','TH','VN','PH','IN','IT','TR','PK','BD'], foodTypes: ['Leather Supplier','Leather Goods','Tanner','Wholesale Leather'] },
  { id: 'maid', isNew: true, accent: '#1E3A8A', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_12_00%20PM.png', label: '#30 House Maid', category: 'House Maid', countries: ['ID','MY','SG','TH','PH','HK','AE','SA','US','GB','AU'], foodTypes: ['House Maid','Maid Service','Pembantu','Housekeeper','Domestic Helper'] },
  { id: 'motorrent', isNew: true, accent: '#FFD600', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_13_32%20PM.png', label: '#31 Motorbike Rental', category: 'Motorbike Rental', countries: ['ID','TH','VN','PH','MY','LA','KH'], foodTypes: ['Motorbike Rental','Scooter Rental','Sewa Motor','Bike Rental'] },
  { id: 'tourguide', isNew: true, accent: '#16A085', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_18_24%20PM.png', label: '#32 Tour Guide', category: 'Tour Guide', countries: ['ID','TH','VN','MY','PH','IN','EG','TR','MX','ES','IT','GR'], foodTypes: ['Tour Guide','Local Guide','Tour Operator','City Tour','Pemandu Wisata'] },
  { id: 'carrent', isNew: true, accent: '#34495E', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_20_35%20PM.png', label: '#33 Car Rental', category: 'Car Rental', countries: ['ID','MY','SG','TH','VN','PH','US','GB','AU','DE','FR','AE'], foodTypes: ['Car Rental','Self-Drive Car','Sewa Mobil','Car Hire','Rental Mobil'] },
  { id: 'wedding', isNew: true, accent: '#FFD600', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_21_51%20PM.png', label: '#34 Wedding Clothes', category: 'Wedding Clothes', countries: ['ID','MY','TH','VN','PH','IN','SG','US','GB','AU'], foodTypes: ['Wedding Clothes','Wedding Dress','Bridal','Tuxedo','Baju Pengantin','Wedding Suit'] },
  { id: 'barber', isNew: true, accent: '#1a1a1a', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2005_51_25%20PM.png', label: '#35 Barber Shop', category: 'Barber Shop', countries: ['ID','MY','SG','TH','VN','PH','US','GB','AU','TR','DE','IT'], foodTypes: ['Barber Shop','Mens Haircut','Barber','Pangkas Rambut'], variants: ['https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2006_05_50%20PM.png', 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_28_40%20PM.png'] },
  { id: 'hairsalon', isNew: true, accent: '#FF69B4', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_30_07%20PM.png', label: '#36 Hair Salon', category: 'Hair Salon', countries: ['ID','MY','SG','TH','VN','PH','KR','JP','US','GB','AU'], foodTypes: ['Hair Salon','Hairdresser','Hair Styling','Salon Rambut','Coloring'] },
  { id: 'nailart', isNew: true, accent: '#E91E63', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_32_19%20PM.png', label: '#37 Nail Art', category: 'Nail Art', countries: ['ID','MY','SG','TH','VN','PH','KR','JP','US','GB','AU'], foodTypes: ['Nail Art','Manicure','Pedicure','Nail Salon','Kuteks'] },
  { id: 'cardriver', isNew: true, accent: '#2C3E50', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2001_33_43%20PM.png', label: '#38 Car Driver', category: 'Car Driver', countries: ['ID','MY','SG','TH','VN','PH','IN','AE','SA','US','GB','AU'], foodTypes: ['Car Driver','Private Driver','Chauffeur','Sopir Pribadi','Driver Hire'] },
  { id: 'glass', isNew: true, accent: '#3498DB', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_05_49%20PM.png', label: '#39 Glass Supplier', category: 'Glass Supplier', countries: ['ID','MY','SG','TH','VN','PH','US','GB','AU'], foodTypes: ['Glass Supplier','Glazier','Window Glass','Kaca','Tukang Kaca'] },
  { id: 'roofrepair', isNew: true, accent: '#A0522D', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_09_50%20PM.png', label: '#40 Roof Repairs', category: 'Roof Repairs', countries: ['ID','MY','SG','TH','VN','PH','US','GB','AU'], foodTypes: ['Roof Repair','Roofing','Tukang Atap','Genteng','Leak Repair'] },
  { id: 'plastering', isNew: true, accent: '#BDC3C7', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_12_28%20PM.png', label: '#41 Plastering', category: 'Plastering', countries: ['ID','MY','SG','TH','VN','PH','US','GB','AU'], foodTypes: ['Plastering','Plasterer','Wall Plaster','Tukang Plester','Render'] },
  { id: 'propertysales', isNew: true, accent: '#16A085', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_24_39%20PM.png', label: '#42 Property Sales', category: 'Property Sales', countries: ['ID','MY','SG','TH','VN','PH','US','GB','AU','AE','HK'], foodTypes: ['Property Sales','Real Estate','House for Sale','Agen Properti','Jual Rumah'] },
  { id: 'propertyrentals', isNew: true, accent: '#2980B9', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_26_11%20PM.png', label: '#43 Property Rentals', category: 'Property Rentals', countries: ['ID','MY','SG','TH','VN','PH','US','GB','AU','AE','HK'], foodTypes: ['Property Rental','Rent','House Rental','Sewa Rumah','Rumah Disewakan'] },
  { id: 'website', isNew: true, accent: '#3498DB', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2011,%202026,%2003_47_59%20PM.png', label: '#44 Website Services', category: 'Website Services', countries: ['ID','MY','SG','TH','VN','PH','US','GB','AU','DE','FR','AE','IN'], foodTypes: ['Website Services','Web Design','Web Developer','Landing Page','Jasa Website','WordPress'] },
  { id: 'jeeptour', isNew: true, accent: '#556B2F', img: 'https://ik.imagekit.io/nepgaxllc/ChatGPT%20Image%20May%2012,%202026,%2006_57_56%20PM.png', label: '#45 Jeep Tour', category: 'Jeep Tour', countries: ['ID','TH','VN','PH','MY','IN','KE','TZ','ZA','US','AU','MX'], foodTypes: ['Jeep Tour','Volcano Tour','Safari','Off Road Tour','Adventure Tour','Jeep Safari','Sunrise Tour','Bromo Tour'] },
]
