/**
 * Indoo — Category Copy System
 *
 * Drives all text content on maker/business profile cards.
 * Layout, colors, and design are untouched — only labels and copy change.
 *
 * Fields per category:
 *   emoji         — icon shown in the category header
 *   slogan        — short subtitle beneath the category name
 *   priceLabel    — label for the price row (replaces "Prices Start")
 *   specialityLabel — label for the activity/speciality row (replaces "Speciality")
 *   hereToLabel   — label for the trade-role row (replaces "Here to")
 *   statusActive  — flash badge when seller is active / out now
 *   statusWants   — flash badge when seller is in invite-out / wants to hang
 *   statusBooked  — flash badge when session is scheduled
 *   ctaActive     — CTA button copy (local, active session)
 *   ctaWants      — CTA button copy (local, invite-out)
 *   ctaScheduled  — CTA button copy (local, scheduled)
 */

const CATEGORY_COPY = {

  // ── Handmade & Craft ─────────────────────────────────────────────────────
  handmade: {
    emoji: '🧵',
    slogan: 'Independent Maker',
    priceLabel: 'Pieces from',
    specialityLabel: 'Craft',
    hereToLabel: 'Here to',
    statusActive: 'Making Now',
    statusWants: 'Available to Order',
    statusBooked: 'Available Soon',
    ctaActive: 'Making Now — Chat Free',
    ctaWants: 'Taking Orders — Message',
    ctaScheduled: 'Available Soon — Message',
  },
  craft_supplies: {
    emoji: '🪡',
    slogan: 'Craft Supplies',
    priceLabel: 'Stock from',
    specialityLabel: 'Supplies',
    hereToLabel: 'Here to',
    statusActive: 'In Stock Now',
    statusWants: 'Taking Orders',
    statusBooked: 'Stock Coming',
    ctaActive: 'In Stock — Chat Free',
    ctaWants: 'Taking Orders — Message',
    ctaScheduled: 'Stock Coming — Enquire',
  },
  art_craft: {
    emoji: '🎨',
    slogan: 'Artist & Maker',
    priceLabel: 'Works from',
    specialityLabel: 'Medium',
    hereToLabel: 'Here to',
    statusActive: 'Creating Now',
    statusWants: 'Open to Commissions',
    statusBooked: 'Available Soon',
    ctaActive: 'Creating Now — Chat Free',
    ctaWants: 'Commission Work — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },

  // ── Commerce & Retail ────────────────────────────────────────────────────
  buy_sell: {
    emoji: '🛒',
    slogan: 'Marketplace Seller',
    priceLabel: 'Items from',
    specialityLabel: 'Category',
    hereToLabel: 'Here to',
    statusActive: 'Selling Now',
    statusWants: 'Open to Offers',
    statusBooked: 'Listing Soon',
    ctaActive: 'Selling Now — Chat Free',
    ctaWants: 'Open to Offers — Message',
    ctaScheduled: 'Listing Soon — Enquire',
  },
  fresh_produce: {
    emoji: '🥬',
    slogan: 'Fresh Produce',
    priceLabel: 'Produce from',
    specialityLabel: 'Produce',
    hereToLabel: 'Selling',
    statusActive: 'Fresh Today',
    statusWants: 'Taking Pre-orders',
    statusBooked: 'Available Tomorrow',
    ctaActive: 'Fresh Today — Chat Free',
    ctaWants: 'Pre-order — Message',
    ctaScheduled: 'Available Tomorrow — Enquire',
  },
  agri_goods: {
    emoji: '🌾',
    slogan: 'Agricultural Goods',
    priceLabel: 'Goods from',
    specialityLabel: 'Goods',
    hereToLabel: 'Selling',
    statusActive: 'Available Today',
    statusWants: 'Taking Orders',
    statusBooked: 'Harvest Soon',
    ctaActive: 'Available Today — Chat Free',
    ctaWants: 'Place an Order — Message',
    ctaScheduled: 'Harvest Coming — Enquire',
  },
  fashion: {
    emoji: '👗',
    slogan: 'Fashion Seller',
    priceLabel: 'Styles from',
    specialityLabel: 'Style',
    hereToLabel: 'Here to',
    statusActive: 'Selling Now',
    statusWants: 'New Arrivals Ready',
    statusBooked: 'Drop Coming',
    ctaActive: 'New In — Chat Free',
    ctaWants: 'New Arrivals — Message',
    ctaScheduled: 'Drop Coming — Enquire',
  },
  electronics: {
    emoji: '📱',
    slogan: 'Electronics Seller',
    priceLabel: 'Devices from',
    specialityLabel: 'Category',
    hereToLabel: 'Here to',
    statusActive: 'In Stock Now',
    statusWants: 'Open to Offers',
    statusBooked: 'Stock Incoming',
    ctaActive: 'In Stock — Chat Free',
    ctaWants: 'Make an Offer — Message',
    ctaScheduled: 'Stock Incoming — Enquire',
  },
  vehicles: {
    emoji: '🚗',
    slogan: 'Vehicle Dealer',
    priceLabel: 'Vehicles from',
    specialityLabel: 'Type',
    hereToLabel: 'Here to',
    statusActive: 'Available to View',
    statusWants: 'Send an Enquiry',
    statusBooked: 'Viewing by Appointment',
    ctaActive: 'View Today — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Book a Viewing — Message',
  },
  tools_equip: {
    emoji: '🔧',
    slogan: 'Tools & Equipment',
    priceLabel: 'Equipment from',
    specialityLabel: 'Category',
    hereToLabel: 'Here to',
    statusActive: 'In Stock Now',
    statusWants: 'Taking Orders',
    statusBooked: 'Stock Expected',
    ctaActive: 'In Stock — Chat Free',
    ctaWants: 'Order Now — Message',
    ctaScheduled: 'Stock Expected — Enquire',
  },
  antiques: {
    emoji: '🏺',
    slogan: 'Antique Dealer',
    priceLabel: 'Pieces from',
    specialityLabel: 'Period',
    hereToLabel: 'Here to',
    statusActive: 'Open to View',
    statusWants: 'Send an Enquiry',
    statusBooked: 'New Pieces Coming',
    ctaActive: 'View Today — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'New Pieces — Enquire',
  },
  import_export: {
    emoji: '📦',
    slogan: 'Import & Export',
    priceLabel: 'Orders from',
    specialityLabel: 'Trade',
    hereToLabel: 'Here to',
    statusActive: 'Open for Business',
    statusWants: 'Taking Enquiries',
    statusBooked: 'Available Soon',
    ctaActive: 'Open Now — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  vintage: {
    emoji: '🕰️',
    slogan: 'Vintage & Preloved',
    priceLabel: 'Pieces from',
    specialityLabel: 'Era',
    hereToLabel: 'Here to',
    statusActive: 'Open to View',
    statusWants: 'Taking Enquiries',
    statusBooked: 'New Stock Coming',
    ctaActive: 'Browse Today — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'New Stock — Enquire',
  },
  hardware: {
    emoji: '🔩',
    slogan: 'Hardware & Supplies',
    priceLabel: 'Stock from',
    specialityLabel: 'Category',
    hereToLabel: 'Here to',
    statusActive: 'In Stock Now',
    statusWants: 'Taking Orders',
    statusBooked: 'Stock Expected',
    ctaActive: 'In Stock — Chat Free',
    ctaWants: 'Order Now — Message',
    ctaScheduled: 'Stock Expected — Enquire',
  },

  // ── Trades & Home Services ───────────────────────────────────────────────
  trades: {
    emoji: '🔨',
    slogan: 'Skilled Tradesperson',
    priceLabel: 'Jobs from',
    specialityLabel: 'Trade',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'Booked — Enquire',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Book a Job — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  auto_repair: {
    emoji: '🔧',
    slogan: 'Auto Repair & Service',
    priceLabel: 'Repairs from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Open Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'Slots Available',
    ctaActive: 'Open Now — Chat Free',
    ctaWants: 'Book a Service — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  cleaning: {
    emoji: '🧹',
    slogan: 'Cleaning Service',
    priceLabel: 'Cleans from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available Today',
    statusWants: 'Taking Bookings',
    statusBooked: 'Available Soon',
    ctaActive: 'Book Today — Chat Free',
    ctaWants: 'Book a Clean — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  garden: {
    emoji: '🌿',
    slogan: 'Garden & Landscaping',
    priceLabel: 'Visits from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available Today',
    statusWants: 'Taking Bookings',
    statusBooked: 'Booked Up — Enquire',
    ctaActive: 'Available Today — Chat Free',
    ctaWants: 'Book a Visit — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  security: {
    emoji: '🛡️',
    slogan: 'Security Service',
    priceLabel: 'Service from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Enquiries',
    statusBooked: 'Consulting',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Book a Consult — Message',
  },
  laundry: {
    emoji: '👕',
    slogan: 'Laundry & Dry Clean',
    priceLabel: 'Service from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Open Now',
    statusWants: 'Taking Drop-offs',
    statusBooked: 'Open Tomorrow',
    ctaActive: 'Open Now — Chat Free',
    ctaWants: 'Drop Off — Message',
    ctaScheduled: 'Open Tomorrow — Enquire',
  },
  tailoring: {
    emoji: '✂️',
    slogan: 'Tailor & Seamstress',
    priceLabel: 'Alterations from',
    specialityLabel: 'Speciality',
    hereToLabel: 'Service',
    statusActive: 'Open for Fittings',
    statusWants: 'Taking Appointments',
    statusBooked: 'By Appointment',
    ctaActive: 'Book a Fitting — Chat Free',
    ctaWants: 'Book a Fitting — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  childcare: {
    emoji: '🧸',
    slogan: 'Childcare Provider',
    priceLabel: 'Care from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Enquiries',
    statusBooked: 'Places Available',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Register Interest — Message',
  },
  eldercare: {
    emoji: '❤️',
    slogan: 'Elder Care Professional',
    priceLabel: 'Care from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Enquiries',
    statusBooked: 'Places Available',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Register Interest — Message',
  },
  pet_care: {
    emoji: '🐾',
    slogan: 'Pet Care Professional',
    priceLabel: 'Sessions from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'Slots Available',
    ctaActive: 'Book Today — Chat Free',
    ctaWants: 'Book a Session — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  transport: {
    emoji: '🚐',
    slogan: 'Transport Service',
    priceLabel: 'Rides from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'On a Job',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Book a Ride — Message',
    ctaScheduled: 'Schedule a Ride — Message',
  },

  // ── Health & Wellness ────────────────────────────────────────────────────
  healthcare: {
    emoji: '🏥',
    slogan: 'Healthcare Professional',
    priceLabel: 'Consultations from',
    specialityLabel: 'Practice',
    hereToLabel: 'Service',
    statusActive: 'Consulting Now',
    statusWants: 'Taking Appointments',
    statusBooked: 'Fully Booked — Enquire',
    ctaActive: 'Book Today — Chat Free',
    ctaWants: 'Book Appointment — Message',
    ctaScheduled: 'Clinic Day — Book Now',
  },
  beauty: {
    emoji: '💅',
    slogan: 'Beauty Professional',
    priceLabel: 'Treatments from',
    specialityLabel: 'Treatment',
    hereToLabel: 'Service',
    statusActive: 'Open Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'Slots Available',
    ctaActive: 'Book Today — Chat Free',
    ctaWants: 'Book a Session — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  fitness_pt: {
    emoji: '💪',
    slogan: 'Fitness Trainer',
    priceLabel: 'Sessions from',
    specialityLabel: 'Training',
    hereToLabel: 'Service',
    statusActive: 'Training Now',
    statusWants: 'Taking New Clients',
    statusBooked: 'Slots Available',
    ctaActive: 'Train Today — Chat Free',
    ctaWants: 'Book a Session — Message',
    ctaScheduled: 'Book a Session — Message',
  },
  mental_health: {
    emoji: '🧠',
    slogan: 'Wellness Professional',
    priceLabel: 'Sessions from',
    specialityLabel: 'Approach',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking New Clients',
    statusBooked: 'By Appointment',
    ctaActive: 'Book Today — Chat Free',
    ctaWants: 'Book a Session — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  alt_medicine: {
    emoji: '🌿',
    slogan: 'Alternative Medicine',
    priceLabel: 'Sessions from',
    specialityLabel: 'Practice',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'By Appointment',
    ctaActive: 'Book Today — Chat Free',
    ctaWants: 'Book a Session — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  veterinary: {
    emoji: '🐕',
    slogan: 'Veterinary Professional',
    priceLabel: 'Consultations from',
    specialityLabel: 'Animals',
    hereToLabel: 'Service',
    statusActive: 'Open Now',
    statusWants: 'Taking Appointments',
    statusBooked: 'Clinic Day',
    ctaActive: 'Book Today — Chat Free',
    ctaWants: 'Book Appointment — Message',
    ctaScheduled: 'Clinic Day — Book Now',
  },
  pharmacy: {
    emoji: '💊',
    slogan: 'Pharmacist',
    priceLabel: 'Dispensing from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Open Now',
    statusWants: 'Taking Enquiries',
    statusBooked: 'Open Tomorrow',
    ctaActive: 'Open Now — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Open Tomorrow — Enquire',
  },

  // ── Food, Hospitality & Events ───────────────────────────────────────────
  catering: {
    emoji: '🍽️',
    slogan: 'Catering Professional',
    priceLabel: 'Covers from',
    specialityLabel: 'Cuisine',
    hereToLabel: 'Service',
    statusActive: 'Taking Bookings',
    statusWants: 'Send a Brief',
    statusBooked: 'Available for Events',
    ctaActive: 'Book Today — Chat Free',
    ctaWants: 'Send a Brief — Message',
    ctaScheduled: 'Available for Events — Enquire',
  },
  restaurant: {
    emoji: '🍜',
    slogan: 'Restaurant & Dining',
    priceLabel: 'Menus from',
    specialityLabel: 'Cuisine',
    hereToLabel: 'Serving',
    statusActive: 'Open Now',
    statusWants: 'Taking Reservations',
    statusBooked: 'Opens Soon',
    ctaActive: 'Reserve a Table — Free',
    ctaWants: 'Reserve a Table — Message',
    ctaScheduled: 'Opens Soon — Reserve',
  },
  hotel_accom: {
    emoji: '🏨',
    slogan: 'Hotel & Accommodation',
    priceLabel: 'Rooms from',
    specialityLabel: 'Accommodation',
    hereToLabel: 'Offering',
    statusActive: 'Rooms Available',
    statusWants: 'Check Availability',
    statusBooked: 'Opening Soon',
    ctaActive: 'Book Now — Chat Free',
    ctaWants: 'Check Availability — Message',
    ctaScheduled: 'Opening Soon — Enquire',
  },
  tourism_guide: {
    emoji: '🗺️',
    slogan: 'Tour Guide',
    priceLabel: 'Tours from',
    specialityLabel: 'Tours',
    hereToLabel: 'Guiding',
    statusActive: 'Guiding Today',
    statusWants: 'Taking Bookings',
    statusBooked: 'Tour Available',
    ctaActive: 'Book a Tour — Chat Free',
    ctaWants: 'Book a Tour — Message',
    ctaScheduled: 'Tour Available — Book Now',
  },
  event_planning: {
    emoji: '🎉',
    slogan: 'Event Planner',
    priceLabel: 'Events from',
    specialityLabel: 'Events',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking New Projects',
    statusBooked: 'In Production',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Send a Brief — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  bar_nightclub: {
    emoji: '🍸',
    slogan: 'Bar & Nightlife',
    priceLabel: 'Entry from',
    specialityLabel: 'Venue',
    hereToLabel: 'Open',
    statusActive: 'Open Tonight',
    statusWants: 'Book a Table',
    statusBooked: 'Opens Tonight',
    ctaActive: 'Open Tonight — Chat Free',
    ctaWants: 'Book a Table — Message',
    ctaScheduled: 'Opens Tonight — Reserve',
  },

  // ── Creative & Media ─────────────────────────────────────────────────────
  creative: {
    emoji: '🎨',
    slogan: 'Creative Professional',
    priceLabel: 'Projects from',
    specialityLabel: 'Discipline',
    hereToLabel: 'Here to',
    statusActive: 'Available Now',
    statusWants: 'Open to Projects',
    statusBooked: 'In Production',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Commission Work — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  content_creator: {
    emoji: '📸',
    slogan: 'Content Creator',
    priceLabel: 'Collabs from',
    specialityLabel: 'Platform',
    hereToLabel: 'Creating',
    statusActive: 'Creating Now',
    statusWants: 'Open to Collabs',
    statusBooked: 'Booked — Enquire',
    ctaActive: 'Collab Now — Chat Free',
    ctaWants: 'Book a Collab — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  music_perform: {
    emoji: '🎵',
    slogan: 'Musician & Performer',
    priceLabel: 'Bookings from',
    specialityLabel: 'Genre',
    hereToLabel: 'Performing',
    statusActive: 'Available to Book',
    statusWants: 'Taking Gigs',
    statusBooked: 'On Tour',
    ctaActive: 'Book a Set — Chat Free',
    ctaWants: 'Book a Gig — Message',
    ctaScheduled: 'Available — Book Now',
  },
  writing: {
    emoji: '✍️',
    slogan: 'Writer & Author',
    priceLabel: 'Pieces from',
    specialityLabel: 'Genre',
    hereToLabel: 'Writing',
    statusActive: 'Available Now',
    statusWants: 'Taking Commissions',
    statusBooked: 'On Deadline',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Commission a Piece — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  fashion_design: {
    emoji: '👗',
    slogan: 'Fashion Designer',
    priceLabel: 'Commissions from',
    specialityLabel: 'Style',
    hereToLabel: 'Designing',
    statusActive: 'Available Now',
    statusWants: 'Taking Commissions',
    statusBooked: 'In Production',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Commission a Piece — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  photography: {
    emoji: '📷',
    slogan: 'Photographer',
    priceLabel: 'Shoots from',
    specialityLabel: 'Speciality',
    hereToLabel: 'Shooting',
    statusActive: 'Available Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'Booked Up',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Book a Shoot — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  music: {
    emoji: '🎸',
    slogan: 'Musician & Artist',
    priceLabel: 'Gigs from',
    specialityLabel: 'Genre',
    hereToLabel: 'Performing',
    statusActive: 'Available Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'On Tour',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Book a Performance — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  wellness: {
    emoji: '🧘',
    slogan: 'Wellness Professional',
    priceLabel: 'Sessions from',
    specialityLabel: 'Practice',
    hereToLabel: 'Offering',
    statusActive: 'Available Now',
    statusWants: 'Taking Bookings',
    statusBooked: 'By Appointment',
    ctaActive: 'Book a Session — Chat Free',
    ctaWants: 'Taking Bookings — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },

  // ── Professional & Business ──────────────────────────────────────────────
  professional: {
    emoji: '💼',
    slogan: 'Business Professional',
    priceLabel: 'Fees from',
    specialityLabel: 'Expertise',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Consultations',
    statusBooked: 'By Appointment',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Book a Consultation — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  business: {
    emoji: '💼',
    slogan: 'Business Consultant',
    priceLabel: 'Packages from',
    specialityLabel: 'Expertise',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking New Clients',
    statusBooked: 'By Appointment',
    ctaActive: 'Book a Call — Chat Free',
    ctaWants: 'Book a Call — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  technology: {
    emoji: '💻',
    slogan: 'Technology Professional',
    priceLabel: 'Projects from',
    specialityLabel: 'Speciality',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking New Projects',
    statusBooked: 'On a Project',
    ctaActive: 'Book a Call — Chat Free',
    ctaWants: 'Start a Project — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  legal: {
    emoji: '⚖️',
    slogan: 'Legal Professional',
    priceLabel: 'Consultations from',
    specialityLabel: 'Practice Area',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Consultations',
    statusBooked: 'By Appointment',
    ctaActive: 'Book a Consult — Chat Free',
    ctaWants: 'Book Consultation — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  engineering: {
    emoji: '⚙️',
    slogan: 'Engineer',
    priceLabel: 'Projects from',
    specialityLabel: 'Discipline',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking New Projects',
    statusBooked: 'On a Project',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  sales_leads: {
    emoji: '📊',
    slogan: 'Sales Professional',
    priceLabel: 'Packages from',
    specialityLabel: 'Industry',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Open to Partnerships',
    statusBooked: 'On a Campaign',
    ctaActive: 'Book a Call — Chat Free',
    ctaWants: 'Let\'s Connect — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  consulting: {
    emoji: '🧩',
    slogan: 'Consultant',
    priceLabel: 'Retainers from',
    specialityLabel: 'Expertise',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Consultations',
    statusBooked: 'By Appointment',
    ctaActive: 'Book a Consult — Chat Free',
    ctaWants: 'Book Consultation — Message',
    ctaScheduled: 'Book Ahead — Message',
  },
  real_estate: {
    emoji: '🏡',
    slogan: 'Real Estate Agent',
    priceLabel: 'Properties from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available to View',
    statusWants: 'Send Enquiry',
    statusBooked: 'By Appointment',
    ctaActive: 'Book a Viewing — Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Book a Viewing — Message',
  },
  marketing: {
    emoji: '📣',
    slogan: 'Marketing Professional',
    priceLabel: 'Campaigns from',
    specialityLabel: 'Speciality',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking New Briefs',
    statusBooked: 'On a Campaign',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Send a Brief — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  media_pro: {
    emoji: '📹',
    slogan: 'Media Professional',
    priceLabel: 'Projects from',
    specialityLabel: 'Medium',
    hereToLabel: 'Service',
    statusActive: 'Available Now',
    statusWants: 'Taking Briefs',
    statusBooked: 'In Production',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Commission Work — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },
  property: {
    emoji: '🏠',
    slogan: 'Property Professional',
    priceLabel: 'Properties from',
    specialityLabel: 'Service',
    hereToLabel: 'Service',
    statusActive: 'Available to View',
    statusWants: 'Send Enquiry',
    statusBooked: 'By Appointment',
    ctaActive: 'View Today — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Book a Viewing — Message',
  },

  // ── Work & Employment ────────────────────────────────────────────────────
  hiring: {
    emoji: '📋',
    slogan: 'Hiring Manager',
    priceLabel: 'Salaries from',
    specialityLabel: 'Role',
    hereToLabel: 'Hiring for',
    statusActive: 'Interviewing Now',
    statusWants: 'Accepting Applications',
    statusBooked: 'Hiring Soon',
    ctaActive: 'Apply Today — Chat Free',
    ctaWants: 'Apply Now — Message',
    ctaScheduled: 'Hiring Soon — Register',
  },
  freelance: {
    emoji: '💡',
    slogan: 'Freelancer',
    priceLabel: 'Projects from',
    specialityLabel: 'Skills',
    hereToLabel: 'Available for',
    statusActive: 'Available for Work',
    statusWants: 'Open to Projects',
    statusBooked: 'On a Project',
    ctaActive: 'Hire Today — Chat Free',
    ctaWants: 'Send a Brief — Message',
    ctaScheduled: 'Available Soon — Enquire',
  },

  // ── Education ────────────────────────────────────────────────────────────
  education: {
    emoji: '📚',
    slogan: 'Educator & Tutor',
    priceLabel: 'Lessons from',
    specialityLabel: 'Subject',
    hereToLabel: 'Teaching',
    statusActive: 'Teaching Now',
    statusWants: 'Taking New Students',
    statusBooked: 'Classes Available',
    ctaActive: 'Book a Lesson — Chat Free',
    ctaWants: 'Book a Lesson — Message',
    ctaScheduled: 'Classes Available — Book',
  },
  coaching: {
    emoji: '🎯',
    slogan: 'Coach & Mentor',
    priceLabel: 'Sessions from',
    specialityLabel: 'Speciality',
    hereToLabel: 'Coaching',
    statusActive: 'Available Now',
    statusWants: 'Taking New Clients',
    statusBooked: 'Slots Available',
    ctaActive: 'Book a Session — Chat Free',
    ctaWants: 'Book a Session — Message',
    ctaScheduled: 'Slots Available — Book',
  },

  // ── Social & Dating ──────────────────────────────────────────────────────
  dating: {
    emoji: '💛',
    slogan: 'Looking to Connect',
    priceLabel: '',
    specialityLabel: 'Interests',
    hereToLabel: 'Here for',
    statusActive: 'Out Now',
    statusWants: 'Want to Hang',
    statusBooked: 'Out Later',
    ctaActive: 'Say Hello — Free',
    ctaWants: 'Send a Message — Free',
    ctaScheduled: 'Out Later — Message',
  },
  meet_new: {
    emoji: '👋',
    slogan: 'Meeting New People',
    priceLabel: '',
    specialityLabel: 'Interests',
    hereToLabel: 'Here for',
    statusActive: 'Hanging Out',
    statusWants: 'Want to Hang',
    statusBooked: 'Out Later',
    ctaActive: 'Say Hello — Free',
    ctaWants: 'Let\'s Hang — Message',
    ctaScheduled: 'Out Later — Message',
  },
  friendship: {
    emoji: '🤝',
    slogan: 'Making Friends',
    priceLabel: '',
    specialityLabel: 'Interests',
    hereToLabel: 'Here for',
    statusActive: 'Hanging Out',
    statusWants: 'Want to Hang',
    statusBooked: 'Out Later',
    ctaActive: 'Say Hello — Free',
    ctaWants: 'Let\'s Hang — Message',
    ctaScheduled: 'Out Later — Message',
  },
}

/**
 * Determines which slide-up page type to show on a profile card.
 *   'shop'     — maker / seller product grid  🛍️
 *   'menu'     — food / drink menu            📋
 *   'services' — service list                 🗒️
 *   null       — no tab (social profiles)
 */
const PAGE_TYPE = {
  // Shop — physical goods / sellers
  handmade:       'shop',
  craft_supplies: 'shop',
  art_craft:      'shop',
  buy_sell:       'shop',
  fashion:        'shop',
  electronics:    'shop',
  vehicles:       'shop',
  tools_equip:    'shop',
  antiques:       'shop',
  import_export:  'shop',
  agri_goods:     'shop',
  vintage:        'shop',
  hardware:       'shop',

  // Menu — food, drink & hospitality
  restaurant:    'menu',
  catering:      'menu',
  bar_nightclub: 'menu',
  hotel_accom:   'menu',
  fresh_produce: 'menu',
  food_drink:    'menu',

  // Services — trade, health, professional, creative
  trades:         'services',
  auto_repair:    'services',
  cleaning:       'services',
  garden:         'services',
  security:       'services',
  laundry:        'services',
  tailoring:      'services',
  childcare:      'services',
  eldercare:      'services',
  pet_care:       'services',
  transport:      'services',
  healthcare:     'services',
  beauty:         'services',
  fitness_pt:     'services',
  mental_health:  'services',
  alt_medicine:   'services',
  veterinary:     'services',
  pharmacy:       'services',
  professional:   'services',
  business:       'services',
  technology:     'services',
  legal:          'services',
  engineering:    'services',
  sales_leads:    'services',
  consulting:     'services',
  real_estate:    'services',
  marketing:      'services',
  media_pro:      'services',
  property:       'services',
  hiring:         'services',
  freelance:      'services',
  education:      'services',
  coaching:       'services',
  creative:       'services',
  content_creator:'services',
  music_perform:  'services',
  music:          'services',
  photography:    'services',
  writing:        'services',
  fashion_design: 'services',
  wellness:       'services',
  tourism_guide:  'services',
  event_planning: 'services',
  // dating, meet_new, friendship → null (omitted — default)
}

/**
 * Get the copy config for a given lookingFor category.
 * Falls back to a sensible default if the category isn't defined.
 */
export function getCategoryCopy(lookingFor) {
  const base = CATEGORY_COPY[lookingFor] ?? {
    emoji: '🏪',
    slogan: 'Seller Profile',
    priceLabel: 'Prices from',
    specialityLabel: 'Speciality',
    hereToLabel: 'Here to',
    statusActive: 'Available Now',
    statusWants: 'Taking Enquiries',
    statusBooked: 'Available Soon',
    ctaActive: 'Available Now — Chat Free',
    ctaWants: 'Send Enquiry — Message',
    ctaScheduled: 'Available Soon — Enquire',
  }
  return { ...base, pageType: PAGE_TYPE[lookingFor] ?? null }
}
