import { offset, now, tonight } from "./mockHelpers"

export const DEMO_MAKER_SESSIONS = [
  // Jakarta — 5 sessions
  {
    id: 'maker-jkt-1', userId: 'maker-user-1',
    displayName: 'Sari', age: 28,
    photoURL: 'https://picsum.photos/seed/bag1/400/300',
    priceFrom: '350.000', priceTo: '1.200.000',
    instagram: 'saribagsstudio', tiktok: 'saribags', facebook: '', website: 'https://saribags.id',
    isVerified: true,
    brandName: 'Sari Bags Studio',
    bio: 'Handcrafted leather handbags made to order. Based in Jakarta Selatan.',
    activityType: 'handbags', activities: ['handbags'],
    productWord: 'Handbag', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'leather bags', 'custom bags', 'jakarta bags'],
    area: 'Jakarta Selatan', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.2607, lng: 106.8107,
    fuzzedLat: -6.2607, fuzzedLng: 106.8107,
    distanceKm: 2.1, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 20 * 60 * 1000,
  },
  {
    id: 'maker-jkt-2', userId: 'maker-user-2',
    displayName: 'Dewi', age: 32,
    photoURL: 'https://picsum.photos/seed/bag2/400/300',
    priceFrom: '580.000', priceTo: '2.500.000',
    instagram: 'dewileatherco', tiktok: 'dewileather', facebook: 'DewíLeatherCo', website: '',
    isVerified: true,
    brandName: 'Dewi Leather Co',
    bio: 'Premium leather goods — handbags, wallets, belts. Custom orders welcome.',
    activityType: 'handbags', activities: ['handbags', 'leatherwork'],
    productWord: 'Leather', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'leather', 'wallets', 'wholesale'],
    area: 'Kemang', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.2567, lng: 106.8130,
    fuzzedLat: -6.2567, fuzzedLng: 106.8130,
    distanceKm: 1.8, expiresAtMs: now + 90 * 60 * 1000, startedAtMs: now - 10 * 60 * 1000,
  },
  {
    id: 'maker-jkt-3', userId: 'maker-user-3',
    displayName: 'Rina', age: 25,
    photoURL: 'https://picsum.photos/seed/bag3/400/300',
    priceFrom: '220.000', priceTo: '850.000',
    instagram: 'rinacrafthouse', tiktok: '', facebook: 'RinaCraftHouse', website: '',
    isVerified: true,
    brandName: 'Rina Craft House',
    bio: 'Woven rattan and fabric bags. Eco-friendly materials only.',
    activityType: 'handbags', activities: ['handbags', 'craft'],
    productWord: 'Rattan', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'rattan', 'eco bags', 'woven bags'],
    area: 'Menteng', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out',
    message: 'Available today to meet buyers and retailers',
    lat: -6.1942, lng: 106.8321,
    fuzzedLat: -6.1942, fuzzedLng: 106.8321,
    distanceKm: 3.4, expiresAtMs: now + 120 * 60 * 1000, startedAtMs: null,
  },
  {
    id: 'maker-jkt-4', userId: 'maker-user-4',
    displayName: 'Putri', age: 30,
    photoURL: 'https://picsum.photos/seed/bag4/400/300',
    priceFrom: '420.000', priceTo: '1.800.000',
    instagram: 'putribatikbags', tiktok: '', facebook: '', website: 'https://putribatik.com',
    isVerified: true,
    brandName: 'Putri Batik Bags',
    bio: 'Traditional batik handbags and totes. Unique Indonesian designs.',
    activityType: 'handbags', activities: ['handbags', 'textile_art'],
    productWord: 'Batik', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'batik', 'tote bags', 'traditional'],
    area: 'Senayan', city: 'Jakarta', country: 'Indonesia',
    status: 'scheduled', scheduledFor: tonight(14, 0),
    lat: -6.2183, lng: 106.8025,
    fuzzedLat: -6.2183, fuzzedLng: 106.8025,
    distanceKm: 2.7, expiresAtMs: tonight(14, 0) + 180 * 60 * 1000, startedAtMs: null,
  },
  {
    id: 'maker-jkt-5', userId: 'maker-user-5',
    displayName: 'Nisa', age: 27,
    photoURL: 'https://picsum.photos/seed/bag5/400/300',
    priceFrom: '680.000', priceTo: '3.200.000',
    brandName: 'Nisa Accessories',
    bio: 'Handmade beaded bags and clutches for events and weddings.',
    activityType: 'handbags', activities: ['handbags', 'jewellery'],
    productWord: 'Clutch', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'clutch', 'beaded bags', 'wedding bags'],
    area: 'Pluit', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.1230, lng: 106.7986,
    fuzzedLat: -6.1230, fuzzedLng: 106.7986,
    distanceKm: 4.1, expiresAtMs: now + 75 * 60 * 1000, startedAtMs: now - 5 * 60 * 1000,
  },

  // Bali — 4 sessions
  {
    id: 'maker-bali-1', userId: 'maker-user-6',
    displayName: 'Kadek', age: 29,
    photoURL: 'https://picsum.photos/seed/bag6/400/300',
    priceFrom: '290.000', priceTo: '950.000',
    brandName: 'Bali Boho Bags',
    bio: 'Boho-style handwoven bags. Wholesale available for boutiques.',
    activityType: 'handbags', activities: ['handbags', 'craft'],
    productWord: 'Boho', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'boho bags', 'bali style', 'wholesale'],
    area: 'Seminyak', city: 'Bali', country: 'Indonesia',
    status: 'active',
    lat: -8.6915, lng: 115.1686,
    fuzzedLat: -8.6915, fuzzedLng: 115.1686,
    distanceKm: 1.2, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 30 * 60 * 1000,
  },
  {
    id: 'maker-bali-2', userId: 'maker-user-7',
    displayName: 'Made', age: 35,
    photoURL: 'https://picsum.photos/seed/bag7/400/300',
    priceFrom: '750.000', priceTo: '4.500.000',
    brandName: 'Made Leather Bali',
    bio: 'Artisan leather bags crafted in Ubud. Export quality.',
    activityType: 'handbags', activities: ['handbags', 'leatherwork'],
    productWord: 'Leather', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'leather', 'ubud craft', 'export'],
    area: 'Ubud', city: 'Bali', country: 'Indonesia',
    status: 'invite_out',
    message: 'Open for meetings with buyers this week',
    lat: -8.5069, lng: 115.2625,
    fuzzedLat: -8.5069, fuzzedLng: 115.2625,
    distanceKm: 5.3, expiresAtMs: now + 180 * 60 * 1000, startedAtMs: null,
  },
  {
    id: 'maker-bali-3', userId: 'maker-user-8',
    displayName: 'Wayan', age: 31,
    photoURL: 'https://picsum.photos/seed/bag8/400/300',
    priceFrom: '185.000', priceTo: '650.000',
    brandName: 'Wayan Rattan Works',
    bio: 'Handmade rattan and bamboo bags. Sustainable sourcing.',
    activityType: 'handbags', activities: ['handbags'],
    productWord: 'Rattan', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'rattan', 'bamboo bags', 'sustainable'],
    area: 'Canggu', city: 'Bali', country: 'Indonesia',
    status: 'active',
    lat: -8.6478, lng: 115.1385,
    fuzzedLat: -8.6478, fuzzedLng: 115.1385,
    distanceKm: 3.8, expiresAtMs: now + 45 * 60 * 1000, startedAtMs: now - 15 * 60 * 1000,
  },
  {
    id: 'maker-bali-4', userId: 'maker-user-9',
    displayName: 'Ayu', age: 26,
    photoURL: 'https://picsum.photos/seed/bag9/400/300',
    priceFrom: '310.000', priceTo: '1.100.000',
    brandName: 'Ayu Bag Studio',
    bio: 'Fabric patchwork and ikat bags. Unique handmade designs.',
    activityType: 'handbags', activities: ['handbags', 'sewing'],
    productWord: 'Ikat', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'ikat', 'patchwork', 'fabric bags'],
    area: 'Kuta', city: 'Bali', country: 'Indonesia',
    status: 'scheduled', scheduledFor: tonight(10, 0),
    lat: -8.7215, lng: 115.1700,
    fuzzedLat: -8.7215, fuzzedLng: 115.1700,
    distanceKm: 2.5, expiresAtMs: tonight(10, 0) + 120 * 60 * 1000, startedAtMs: null,
  },

  // Surabaya — 3 sessions
  {
    id: 'maker-sby-1', userId: 'maker-user-10',
    displayName: 'Indah', age: 33,
    photoURL: 'https://picsum.photos/seed/bag10/400/300',
    priceFrom: '450.000', priceTo: '2.000.000',
    brandName: 'Indah Handbag Factory',
    bio: 'Manufacturer of women\'s handbags. Minimum order 10 pieces.',
    activityType: 'handbags', activities: ['handbags'],
    productWord: 'Handbag', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'manufacturer', 'wholesale', 'surabaya'],
    area: 'Rungkut', city: 'Surabaya', country: 'Indonesia',
    status: 'active',
    lat: -7.3232, lng: 112.7706,
    fuzzedLat: -7.3232, fuzzedLng: 112.7706,
    distanceKm: 3.1, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 25 * 60 * 1000,
  },
  {
    id: 'maker-sby-2', userId: 'maker-user-11',
    displayName: 'Sri', age: 40,
    photoURL: 'https://picsum.photos/seed/bag11/400/300',
    priceFrom: '620.000', priceTo: '3.800.000',
    brandName: 'Sri Classic Bags',
    bio: 'Classic leather handbags and briefcases. Family business since 2005.',
    activityType: 'handbags', activities: ['handbags', 'leatherwork'],
    productWord: 'Briefcase', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'briefcase', 'leather', 'classic'],
    area: 'Genteng', city: 'Surabaya', country: 'Indonesia',
    status: 'invite_out',
    message: 'Looking for retail partners in Surabaya',
    lat: -7.2575, lng: 112.7521,
    fuzzedLat: -7.2575, fuzzedLng: 112.7521,
    distanceKm: 1.9, expiresAtMs: now + 90 * 60 * 1000, startedAtMs: null,
  },
  {
    id: 'maker-sby-3', userId: 'maker-user-12',
    displayName: 'Lestari', age: 24,
    photoURL: 'https://picsum.photos/seed/bag12/400/300',
    priceFrom: '95.000', priceTo: '380.000',
    bio: 'Mini bags and coin purses — kawaii style. Online & meet in person.',
    activityType: 'handbags', activities: ['handbags', 'sewing'],
    productWord: 'Purse', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'mini bags', 'coin purse', 'kawaii'],
    area: 'Gubeng', city: 'Surabaya', country: 'Indonesia',
    status: 'active',
    lat: -7.2714, lng: 112.7527,
    fuzzedLat: -7.2714, fuzzedLng: 112.7527,
    distanceKm: 0.8, expiresAtMs: now + 50 * 60 * 1000, startedAtMs: now - 8 * 60 * 1000,
  },

  // Bandung — 2 sessions
  {
    id: 'maker-bdg-1', userId: 'maker-user-13',
    displayName: 'Tari', age: 29,
    photoURL: 'https://picsum.photos/seed/bag13/400/300',
    priceFrom: '275.000', priceTo: '900.000',
    brandName: 'Tari Denim Bags',
    bio: 'Upcycled denim handbags. Every piece is one of a kind.',
    activityType: 'handbags', activities: ['handbags', 'upcycling'],
    productWord: 'Denim', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'denim bags', 'upcycled', 'sustainable'],
    area: 'Dago', city: 'Bandung', country: 'Indonesia',
    status: 'active',
    lat: -6.8798, lng: 107.6125,
    fuzzedLat: -6.8798, fuzzedLng: 107.6125,
    distanceKm: 2.3, expiresAtMs: now + 70 * 60 * 1000, startedAtMs: now - 12 * 60 * 1000,
  },
  {
    id: 'maker-bdg-2', userId: 'maker-user-14',
    displayName: 'Mega', age: 27,
    photoURL: 'https://picsum.photos/seed/bag14/400/300',
    priceFrom: '380.000', priceTo: '1.500.000',
    brandName: 'Mega Tenun Bags',
    bio: 'Traditional tenun woven bags from West Java. Export quality.',
    activityType: 'handbags', activities: ['handbags', 'textile_art'],
    productWord: 'Tenun', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'tenun', 'woven', 'west java'],
    area: 'Buah Batu', city: 'Bandung', country: 'Indonesia',
    status: 'invite_out',
    message: 'Available to meet buyers and boutique owners',
    lat: -6.9509, lng: 107.6399,
    fuzzedLat: -6.9509, fuzzedLng: 107.6399,
    distanceKm: 4.2, expiresAtMs: now + 100 * 60 * 1000, startedAtMs: null,
  },

  // Medan — 2 sessions
  {
    id: 'maker-mdn-1', userId: 'maker-user-15',
    displayName: 'Aisyah', age: 31,
    photoURL: 'https://picsum.photos/seed/bag15/400/300',
    priceFrom: '520.000', priceTo: '2.800.000',
    brandName: 'Aisyah Songket Bags',
    bio: 'Songket fabric handbags. Traditional North Sumatran craft.',
    activityType: 'handbags', activities: ['handbags', 'textile_art'],
    productWord: 'Songket', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'songket', 'sumatra craft', 'traditional'],
    area: 'Medan Baru', city: 'Medan', country: 'Indonesia',
    status: 'active',
    lat: 3.5880, lng: 98.6722,
    fuzzedLat: 3.5880, fuzzedLng: 98.6722,
    distanceKm: 1.6, expiresAtMs: now + 80 * 60 * 1000, startedAtMs: now - 18 * 60 * 1000,
  },
  {
    id: 'maker-mdn-2', userId: 'maker-user-16',
    displayName: 'Fitri', age: 25,
    photoURL: 'https://picsum.photos/seed/bag16/400/300',
    priceFrom: '150.000', priceTo: '480.000',
    bio: 'Handmade bags using recycled flour sacks. Eco fashion.',
    activityType: 'handbags', activities: ['handbags', 'upcycling'],
    productWord: 'Eco', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'recycled', 'eco fashion', 'upcycled bags'],
    area: 'Helvetia', city: 'Medan', country: 'Indonesia',
    status: 'active',
    lat: 3.6194, lng: 98.6388,
    fuzzedLat: 3.6194, fuzzedLng: 98.6388,
    distanceKm: 2.9, expiresAtMs: now + 55 * 60 * 1000, startedAtMs: now - 22 * 60 * 1000,
  },
  {
    id: 'maker-jkt-6', userId: 'maker-user-17',
    displayName: 'Citra', age: 29,
    photoURL: 'https://picsum.photos/seed/bag17/400/300',
    priceFrom: '890.000', priceTo: '5.000.000',
    bio: 'Luxury tote bags made from batik fabric. Ships worldwide.',
    activityType: 'handbags', activities: ['handbags', 'fashion_design'],
    productWord: 'Tote', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'batik', 'luxury', 'tote'],
    area: 'Kemang', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out',
    lat: -6.2603, lng: 106.8147,
    fuzzedLat: -6.2603, fuzzedLng: 106.8147,
    distanceKm: 1.4, expiresAtMs: now + 70 * 60 * 1000, startedAtMs: now - 10 * 60 * 1000,
  },
  {
    id: 'maker-jkt-7', userId: 'maker-user-18',
    displayName: 'Lina', age: 31,
    photoURL: 'https://picsum.photos/seed/bag18/400/300',
    priceFrom: '430.000', priceTo: '1.600.000',
    bio: 'Minimalist leather clutch bags. Custom orders welcome.',
    activityType: 'leatherwork', activities: ['leatherwork', 'handbags'],
    productWord: 'Clutch', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['leather', 'clutch', 'minimalist', 'custom'],
    area: 'Senayan', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.2297, lng: 106.8011,
    fuzzedLat: -6.2297, fuzzedLng: 106.8011,
    distanceKm: 2.1, expiresAtMs: now + 40 * 60 * 1000, startedAtMs: now - 30 * 60 * 1000,
  },
  {
    id: 'maker-bali-5', userId: 'maker-user-19',
    displayName: 'Ni Made', age: 27,
    photoURL: 'https://picsum.photos/seed/bag19/400/300',
    priceFrom: '340.000', priceTo: '1.200.000',
    bio: 'Woven rattan bags inspired by Balinese craft tradition.',
    activityType: 'handbags', activities: ['handbags', 'craft'],
    lookingFor: 'handmade',
    tags: ['rattan', 'woven', 'balinese', 'bags'],
    area: 'Ubud', city: 'Bali', country: 'Indonesia',
    status: 'scheduled',
    lat: -8.5069, lng: 115.2625,
    fuzzedLat: -8.5069, fuzzedLng: 115.2625,
    distanceKm: 3.2, expiresAtMs: now + 90 * 60 * 1000, startedAtMs: now - 5 * 60 * 1000,
  },
  {
    id: 'maker-sby-4', userId: 'maker-user-20',
    displayName: 'Hana', age: 26,
    photoURL: 'https://picsum.photos/seed/bag20/400/300',
    priceFrom: '260.000', priceTo: '780.000',
    bio: 'Embroidered shoulder bags with floral patterns. Each piece unique.',
    activityType: 'handbags', activities: ['handbags', 'embroidery'],
    lookingFor: 'handmade',
    tags: ['embroidery', 'shoulder bag', 'floral', 'handmade'],
    area: 'Gubeng', city: 'Surabaya', country: 'Indonesia',
    status: 'active',
    lat: -7.2658, lng: 112.7509,
    fuzzedLat: -7.2658, fuzzedLng: 112.7509,
    distanceKm: 1.8, expiresAtMs: now + 50 * 60 * 1000, startedAtMs: now - 15 * 60 * 1000,
  },
  {
    id: 'maker-jkt-8', userId: 'maker-user-21',
    displayName: 'Vina', age: 28,
    photoURL: 'https://picsum.photos/seed/bag21/400/300',
    priceFrom: '310.000', priceTo: '1.050.000',
    bio: 'Hand-painted canvas bags. Bold colours, limited runs.',
    activityType: 'handbags', activities: ['handbags', 'fashion_design'],
    lookingFor: 'handmade',
    tags: ['canvas', 'painted', 'limited edition', 'bags'],
    area: 'Menteng', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.1944, lng: 106.8294,
    fuzzedLat: -6.1944, fuzzedLng: 106.8294,
    distanceKm: 1.1, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 8 * 60 * 1000,
  },
  {
    id: 'maker-jkt-9', userId: 'maker-user-22',
    displayName: 'Rara', age: 24,
    photoURL: 'https://picsum.photos/seed/bag22/400/300',
    priceFrom: '560.000', priceTo: '2.200.000',
    bio: 'Beaded evening bags. Perfect for weddings and events.',
    activityType: 'handbags', activities: ['handbags', 'jewellery'],
    lookingFor: 'handmade',
    tags: ['beaded', 'evening bag', 'wedding', 'handmade'],
    area: 'Sudirman', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out',
    lat: -6.2088, lng: 106.8175,
    fuzzedLat: -6.2088, fuzzedLng: 106.8175,
    distanceKm: 0.9, expiresAtMs: now + 80 * 60 * 1000, startedAtMs: now - 20 * 60 * 1000,
  },
  // ── UK maker — always visible regardless of time ──────────────────────────
  {
    id: 'demo-session-7',
    userId: 'demo-user-9',
    displayName: 'Zara', age: 26,
    photoURL: null,
    photos: ['https://ik.imagekit.io/nepgaxllc/Untitledsdfasdfddd.png', 'https://ik.imagekit.io/nepgaxllc/Untitledsdfasdfdddfsdfsd.png'],
    isVerified: true,
    brandName: 'Zara Clothes',
    tradeRole: 'both',
    priceFrom: '12.000', priceTo: '24.000',
    speakingNative: 'Indonesian',
    speakingSecond: 'English',
    market: 'Local & Export',
    gender: 'female',
    bio: 'Designer and fabric maker for shoes and hats. Contact me for any request.',
    activityType: 'dress_making',
    activities: ['dress_making', 'fashion_design', 'sewing'],
    lookingFor: 'handmade',
    tags: ['clothes', 'dress', 'fashion', 'sewing', 'handmade'],
    tier: 'listing',
    instagram: 'zaraclothesuk', tiktok: 'zaraclothes', facebook: 'ZaraClothesLondon', youtube: 'zaraclothesuk', website: 'https://zaraclothes.co.uk',
    area: 'Soho', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: 51.5133, lng: -0.1320,
    fuzzedLat: 51.5133, fuzzedLng: -0.1320,
    distanceKm: 0.4, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 10 * 60 * 1000,
  },
]

