import { offset, now } from "./mockHelpers"

export const DEMO_BUSINESS_SELLERS = [
  {
    id: 'biz-1',
    displayName: 'Amara Fashion House',
    brandName: 'Amara Fashion',
    lookingFor: 'fashion',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Romantic%20sunset%20lakeside%20embrace.png',
    bio: 'Luxury African prints, modern cuts & occasion wear. Every piece is made to order.',
    productCondition: 'new',
    isOnline: true,
    bizWhatsapp: '+447700900001',
    tags: ['fashion', 'african print', 'dresses', 'occasion wear', 'made to order'],
  },
  {
    id: 'biz-2',
    displayName: 'TechZone London',
    brandName: 'TechZone',
    lookingFor: 'electronics',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasd.png',
    bio: 'Latest smartphones, laptops, accessories & same-day screen repairs.',
    productCondition: 'new',
    isOnline: true,
    bizWhatsapp: '+447700900002',
    tags: ['electronics', 'phones', 'laptops', 'screen repair', 'accessories'],
  },
  {
    id: 'biz-3',
    displayName: "Priya's Beauty Studio",
    brandName: 'Priya Beauty',
    lookingFor: 'beauty',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasdsdasdaasdasdasdasd.png',
    bio: 'Hair braiding, gel nails, lashes & waxing. Walk-ins welcome Mon–Sat.',
    productCondition: 'new',
    isOnline: false,
    bizWhatsapp: '+447700900003',
    tags: ['beauty', 'hair', 'nails', 'lashes', 'waxing', 'salon'],
  },
  {
    id: 'biz-4',
    displayName: 'Urban Bites Kitchen',
    brandName: 'Urban Bites',
    lookingFor: 'catering',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasdsdasdaasdasd.png',
    bio: 'Jollof rice, grills, wraps & homemade sauces. Delivery & events catering.',
    productCondition: 'new',
    isOnline: true,
    bizWhatsapp: '+447700900004',
    tags: ['food', 'catering', 'jollof', 'delivery', 'grills', 'events'],
  },
  {
    id: 'biz-5',
    displayName: 'Green Craft Studio',
    brandName: 'GreenCraft',
    lookingFor: 'art_craft',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Romantic%20sunset%20lakeside%20embrace.png',
    bio: 'Handmade ceramics, art prints & bespoke gifts. Custom orders open year round.',
    productCondition: 'both',
    isOnline: false,
    bizWhatsapp: '+447700900005',
    tags: ['handmade', 'ceramics', 'art', 'prints', 'gifts', 'craft'],
  },
  {
    id: 'biz-6',
    displayName: 'Swift Fix Auto',
    brandName: 'Swift Fix',
    lookingFor: 'auto_repair',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasd.png',
    bio: 'Car servicing, diagnostics, tyres & bodywork. Mobile mechanic — we come to you.',
    productCondition: 'used',
    isOnline: true,
    bizWhatsapp: '+447700900006',
    tags: ['auto repair', 'mechanic', 'tyres', 'servicing', 'car', 'bodywork'],
  },
  {
    id: 'biz-7',
    displayName: 'LexTech Solutions',
    brandName: 'LexTech',
    lookingFor: 'technology',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasdsdasdaasdasdasdasd.png',
    bio: 'Web design, mobile apps, SEO & IT support for small businesses.',
    productCondition: 'new',
    isOnline: false,
    bizWhatsapp: '+447700900007',
    tags: ['technology', 'web design', 'app development', 'seo', 'it support'],
  },
  {
    id: 'biz-8',
    displayName: 'Stitch & Style',
    brandName: 'Stitch & Style',
    lookingFor: 'tailoring',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasdsdasdaasdasd.png',
    bio: 'Bespoke suits, dresses & fast alterations. Trusted by over 500 clients.',
    productCondition: 'new',
    isOnline: true,
    bizWhatsapp: '+447700900008',
    tags: ['tailoring', 'suits', 'dresses', 'alterations', 'bespoke', 'fashion'],
  },
  {
    id: 'biz-9',
    displayName: 'Spark Solar & Energy',
    brandName: 'Spark Energy',
    lookingFor: 'electronics',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Romantic%20sunset%20lakeside%20embrace.png',
    bio: 'Solar panels, inverters, battery storage & smart home installations.',
    productCondition: 'new',
    isOnline: true,
    bizWhatsapp: '+447700900009',
    tags: ['solar', 'energy', 'inverter', 'smart home', 'battery', 'installation'],
  },
  {
    id: 'biz-10',
    displayName: 'Clean & Shine Services',
    brandName: 'Clean & Shine',
    lookingFor: 'cleaning',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasd.png',
    bio: 'Domestic & commercial cleaning. End-of-tenancy, deep cleans & regular schedules.',
    productCondition: 'new',
    isOnline: false,
    bizWhatsapp: '+447700900010',
    tags: ['cleaning', 'domestic', 'end of tenancy', 'deep clean', 'commercial'],
  },
  {
    id: 'biz-11',
    displayName: 'Golden Events & Weddings',
    brandName: 'Golden Events',
    lookingFor: 'event_planning',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasdsdasdaasdasdasdasd.png',
    bio: 'Full wedding & event planning. Venues, décor, catering coordination & photography.',
    productCondition: 'new',
    isOnline: true,
    bizWhatsapp: '+447700900011',
    tags: ['events', 'wedding', 'party', 'venue', 'decoration', 'photography'],
  },
  {
    id: 'biz-12',
    displayName: 'HomeBuilder Trades',
    brandName: 'HomeBuilder',
    lookingFor: 'trades',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/Untitleddsadasdasdsdasdaasdasd.png',
    bio: 'Plumbing, electrics, tiling, plastering & full renovations. Gas Safe registered.',
    productCondition: 'new',
    isOnline: false,
    bizWhatsapp: '+447700900012',
    tags: ['trades', 'plumber', 'electrician', 'tiling', 'plastering', 'renovation'],
  },
  {
    id: 'biz-13',
    displayName: 'Luxe Leather Studio',
    brandName: 'Luxe Leather',
    lookingFor: 'handmade',
    city: 'Jakarta', country: 'Indonesia',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/UntitledxcvzcvzxcvzxcASDASDfasdfsd.png',
    bio: 'Handcrafted leather handbags, purses & accessories. Every piece made to order.',
    productCondition: 'new',
    isOnline: true,
    bizWhatsapp: '+6281234567890',
    instagram: 'luxeleather.id',
    tiktok: 'luxeleather.id',
    facebook: 'LuxeLeatherJakarta',
    website: 'https://luxeleather.id',
    openTime: '9:00 AM',
    closeTime: '7:00 PM',
    tags: ['leather', 'handbags', 'bags', 'purse', 'accessories', 'handmade', 'bespoke'],
  },
]
