import { offset, now, _LDN } from "./mockHelpers"

export const DEMO_CATEGORY_SESSIONS = [

  // ── Handmade ──────────────────────────────────────────────────────────────
  {
    id: 'cat-handmade-1', userId: 'cat-user-handmade', isSeeded: true,
    displayName: 'Zara', age: 28,
    photoURL: 'https://picsum.photos/seed/cat-handmade/400/500',
    photos: ['https://picsum.photos/seed/cat-handmade/400/500'],
    bio: 'I make jewellery, ceramics and one-of-a-kind gifts by hand. Every piece takes 2–5 days. DM to order or visit me at Spitalfields every Sunday.',
    lookingFor: 'handmade',
    activityType: 'craft', activities: ['craft', 'markets'],
    brandName: 'Zara Makes', tradeRole: 'selling', targetAudience: ['women', 'gifts'],
    priceMin: '£18', priceMax: '£120',
    tags: ['jewellery', 'ceramics', 'handmade gifts', 'custom orders'],
    instagram: 'zaramakes_ldn', tiktok: 'zaramakes',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'French',
    area: 'Spitalfields', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-09-14').getTime(),
    distanceKm: 0.9, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'premium',
    ..._LDN(0.01, 0.05),
  },

  // ── Craft Supplies ────────────────────────────────────────────────────────
  {
    id: 'cat-craft-supplies-1', userId: 'cat-user-craftsupplies', isSeeded: true,
    displayName: 'Priya', age: 34,
    photoURL: 'https://picsum.photos/seed/cat-craft-supplies/400/500',
    photos: ['https://picsum.photos/seed/cat-craft-supplies/400/500'],
    bio: 'Wholesale & retail craft supplies — resin, fabrics, threads, tools. I stock 400+ lines. Trade accounts welcome. Based in Walthamstow.',
    lookingFor: 'craft_supplies',
    activityType: 'craft', activities: ['craft', 'wholesale'],
    brandName: 'Priya\'s Craft Depot', tradeRole: 'selling', targetAudience: ['all'],
    priceMin: '£2', priceMax: '£85',
    tags: ['resin', 'fabric', 'thread', 'craft tools', 'wholesale'],
    instagram: 'priyas_craft_depot', website: 'https://priyascraftdepot.co.uk',
    contactPlatform: 'whatsapp',
    speakingNative: 'English', speakingSecond: 'Hindi',
    area: 'Walthamstow', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-11-02').getTime(),
    distanceKm: 4.2, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.04, 0.08),
  },

  // ── Art & Craft ───────────────────────────────────────────────────────────
  {
    id: 'cat-art-craft-1', userId: 'cat-user-artcraft', isSeeded: true,
    displayName: 'Marco', age: 31,
    photoURL: 'https://picsum.photos/seed/cat-art-craft/400/500',
    photos: ['https://picsum.photos/seed/cat-art-craft/400/500'],
    bio: 'Oil paintings, prints and murals. Commission work only — takes 3–6 weeks. I exhibit at Saatchi Gallery twice a year. Studio visits by appointment.',
    lookingFor: 'art_craft',
    activityType: 'art', activities: ['art', 'galleries'],
    brandName: 'Marco Studio', tradeRole: 'selling', targetAudience: ['all'],
    priceMin: '£95', priceMax: '£2,800',
    tags: ['oil painting', 'murals', 'prints', 'commission art'],
    instagram: 'marco.studio.ldn', website: 'https://marcostudio.co.uk',
    contactPlatform: 'instagram',
    speakingNative: 'Italian', speakingSecond: 'English',
    area: 'Chelsea', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-08-21').getTime(),
    distanceKm: 2.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'premium',
    ..._LDN(-0.02, -0.07),
  },

  // ── Buy & Sell ────────────────────────────────────────────────────────────
  {
    id: 'cat-buy-sell-1', userId: 'cat-user-buysell', isSeeded: true,
    displayName: 'Jordan', age: 26,
    photoURL: 'https://picsum.photos/seed/cat-buy-sell/400/500',
    photos: ['https://picsum.photos/seed/cat-buy-sell/400/500'],
    bio: 'I flip electronics, trainers and limited streetwear. Checked & authenticated every item. Cash or bank transfer. Shoreditch meetups only.',
    lookingFor: 'buy_sell',
    activityType: 'retail', activities: ['retail', 'markets'],
    tradeRole: 'both',
    priceMin: '£20', priceMax: '£400',
    tags: ['trainers', 'streetwear', 'electronics', 'authentic'],
    instagram: 'jordan.flips.ldn', tiktok: 'jordanflips',
    contactPlatform: 'telegram',
    speakingNative: 'English',
    area: 'Shoreditch', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-01-10').getTime(),
    distanceKm: 1.6, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'free',
    ..._LDN(0.03, 0.06),
  },

  // ── Fresh Produce ─────────────────────────────────────────────────────────
  {
    id: 'cat-fresh-produce-1', userId: 'cat-user-freshproduce', isSeeded: true,
    displayName: 'Afia', age: 38,
    photoURL: 'https://picsum.photos/seed/cat-fresh-produce/400/500',
    photos: ['https://picsum.photos/seed/cat-fresh-produce/400/500'],
    bio: 'Farm-fresh organic veg, fruit and herbs delivered to your door or collected from Brixton Market every Saturday. Supporting local growers since 2019.',
    lookingFor: 'fresh_produce',
    activityType: 'food', activities: ['food', 'markets'],
    brandName: 'Afia\'s Fresh Box', tradeRole: 'selling',
    priceMin: '£5', priceMax: '£45',
    tags: ['organic', 'veg box', 'local produce', 'farmers market'],
    instagram: 'afiafreshbox', facebook: 'AfiaFreshBox',
    contactPlatform: 'whatsapp',
    speakingNative: 'English', speakingSecond: 'Twi',
    area: 'Brixton', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-07-30').getTime(),
    distanceKm: 3.4, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'premium',
    ..._LDN(-0.04, -0.03),
  },

  // ── Fashion ───────────────────────────────────────────────────────────────
  {
    id: 'cat-fashion-1', userId: 'cat-user-fashion', isSeeded: true,
    displayName: 'Leila', age: 29,
    photoURL: 'https://picsum.photos/seed/cat-fashion/400/500',
    photos: ['https://picsum.photos/seed/cat-fashion/400/500'],
    bio: 'Independent fashion designer — ready-to-wear and made-to-measure. Stocked in 3 boutiques across London. New collection drops every season.',
    lookingFor: 'fashion',
    activityType: 'fashion', activities: ['fashion', 'markets'],
    brandName: 'Leila Atelier', tradeRole: 'selling',
    priceMin: '£65', priceMax: '£380',
    tags: ['fashion', 'made to measure', 'sustainable', 'womenswear'],
    instagram: 'leila.atelier', website: 'https://leilaatelier.com',
    contactPlatform: 'instagram',
    speakingNative: 'Arabic', speakingSecond: 'English',
    area: 'Notting Hill', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-10-15').getTime(),
    distanceKm: 2.8, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'pro',
    ..._LDN(-0.01, -0.12),
  },

  // ── Vintage ───────────────────────────────────────────────────────────────
  {
    id: 'cat-vintage-1', userId: 'cat-user-vintage', isSeeded: true,
    displayName: 'Clara', age: 33,
    photoURL: 'https://picsum.photos/seed/cat-vintage/400/500',
    photos: ['https://picsum.photos/seed/cat-vintage/400/500'],
    bio: 'Curated vintage and pre-loved clothing from the 60s–90s. I sell at Portobello Road on Saturdays and ship UK-wide. Nothing over £95.',
    lookingFor: 'vintage',
    activityType: 'fashion', activities: ['fashion', 'markets'],
    brandName: 'Clara\'s Vintage Rail', tradeRole: 'selling',
    priceMin: '£8', priceMax: '£95',
    tags: ['vintage', 'pre-loved', '90s', 'portobello', 'sustainable fashion'],
    instagram: 'clarasvintagerail', tiktok: 'clarasvintage',
    contactPlatform: 'instagram',
    speakingNative: 'English',
    area: 'Portobello', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-12-01').getTime(),
    distanceKm: 3.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.005, -0.11),
  },

  // ── Trades ────────────────────────────────────────────────────────────────
  {
    id: 'cat-trades-1', userId: 'cat-user-trades', isSeeded: true,
    displayName: 'Danny', age: 42,
    photoURL: 'https://picsum.photos/seed/cat-trades/400/500',
    photos: ['https://picsum.photos/seed/cat-trades/400/500'],
    bio: 'Qualified electrician & plumber. 18 years experience. No job too small — full rewires to fixing a leaking tap. Available weekends. Fully insured.',
    lookingFor: 'trades',
    activityType: 'services', activities: ['services'],
    brandName: 'Danny\'s Trades', tradeRole: 'selling',
    priceMin: '£65/hr', priceMax: '£POA',
    tags: ['electrician', 'plumber', 'handyman', 'fully insured', 'London'],
    facebook: 'DannyTradesLondon',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'Hackney', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-06-12').getTime(),
    distanceKm: 2.6, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'premium',
    ..._LDN(0.05, 0.09),
  },

  // ── Property ──────────────────────────────────────────────────────────────
  {
    id: 'cat-property-1', userId: 'cat-user-property', isSeeded: true,
    displayName: 'Natasha', age: 36,
    photoURL: 'https://picsum.photos/seed/cat-property/400/500',
    photos: ['https://picsum.photos/seed/cat-property/400/500'],
    bio: 'Property consultant with 10 years in London lettings and sales. I help landlords find tenants and buyers find their first home. Free initial consultation.',
    lookingFor: 'property',
    activityType: 'property', activities: ['property'],
    brandName: 'Natasha Property', tradeRole: 'selling',
    priceMin: 'Free consult', priceMax: '1.5% fee',
    tags: ['property', 'lettings', 'first time buyer', 'landlord advice'],
    instagram: 'natasha.property.ldn', linkedin: 'natasha-property',
    contactPlatform: 'phone',
    speakingNative: 'English', speakingSecond: 'Russian',
    area: 'Canary Wharf', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-08-08').getTime(),
    distanceKm: 3.9, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.02, 0.14),
  },

  // ── Real Estate ───────────────────────────────────────────────────────────
  {
    id: 'cat-real-estate-1', userId: 'cat-user-realestate', isSeeded: true,
    displayName: 'Tariq', age: 44,
    photoURL: 'https://picsum.photos/seed/cat-real-estate/400/500',
    photos: ['https://picsum.photos/seed/cat-real-estate/400/500'],
    bio: 'RICS-accredited surveyor and property investment advisor. Specialising in East London buy-to-let and commercial conversions. 20+ years on the market.',
    lookingFor: 'real_estate',
    activityType: 'property', activities: ['property'],
    brandName: 'Tariq Real Estate Group', tradeRole: 'selling',
    priceMin: '£500', priceMax: '£POA',
    tags: ['buy to let', 'commercial', 'surveyor', 'property investment'],
    website: 'https://tariqrealestategroup.co.uk',
    contactPlatform: 'phone',
    speakingNative: 'English', speakingSecond: 'Urdu',
    area: 'Stratford', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-05-20').getTime(),
    distanceKm: 5.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.06, 0.12),
  },

  // ── Beauty ────────────────────────────────────────────────────────────────
  {
    id: 'cat-beauty-1', userId: 'cat-user-beauty', isSeeded: true,
    displayName: 'Yemi', age: 27,
    photoURL: 'https://picsum.photos/seed/cat-beauty/400/500',
    photos: ['https://picsum.photos/seed/cat-beauty/400/500'],
    bio: 'Afro hair specialist, makeup artist and lash technician. Home visits or salon. Bridal packages available. Fully qualified, insured and DBS checked.',
    lookingFor: 'beauty',
    activityType: 'beauty', activities: ['beauty'],
    brandName: 'Yemi Beauty', tradeRole: 'selling',
    priceMin: '£35', priceMax: '£280',
    tags: ['afro hair', 'lashes', 'bridal makeup', 'mobile beauty'],
    instagram: 'yemibeautyldn', tiktok: 'yemibeauty',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'Yoruba',
    area: 'Peckham', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-10-28').getTime(),
    distanceKm: 4.7, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(-0.05, 0.03),
  },

  // ── Healthcare ────────────────────────────────────────────────────────────
  {
    id: 'cat-healthcare-1', userId: 'cat-user-healthcare', isSeeded: true,
    displayName: 'Dr. Aisha', age: 39,
    photoURL: 'https://picsum.photos/seed/cat-healthcare/400/500',
    photos: ['https://picsum.photos/seed/cat-healthcare/400/500'],
    bio: 'Physiotherapist specialising in sports injuries and chronic back pain. 1-to-1 sessions at my Clapham clinic or home visits within Zone 2.',
    lookingFor: 'healthcare',
    activityType: 'health', activities: ['health', 'sports'],
    brandName: 'Aisha Physio', tradeRole: 'selling',
    priceMin: '£75', priceMax: '£150',
    tags: ['physiotherapy', 'sports injury', 'back pain', 'home visits'],
    website: 'https://aishaphysio.co.uk',
    contactPlatform: 'phone',
    speakingNative: 'English', speakingSecond: 'Somali',
    area: 'Clapham', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-09-03').getTime(),
    distanceKm: 3.6, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(-0.06, -0.04),
  },

  // ── Fitness & PT ──────────────────────────────────────────────────────────
  {
    id: 'cat-fitness-pt-1', userId: 'cat-user-fitnesspt', isSeeded: true,
    displayName: 'Marcus', age: 30,
    photoURL: 'https://picsum.photos/seed/cat-fitness-pt/400/500',
    photos: ['https://picsum.photos/seed/cat-fitness-pt/400/500'],
    bio: 'Personal trainer specialising in weight loss and strength. Outdoor sessions in Hyde Park or your own gym. Online plans available. First session free.',
    lookingFor: 'fitness_pt',
    activityType: 'fitness', activities: ['fitness', 'sports'],
    brandName: 'Marcus Fit', tradeRole: 'selling',
    priceMin: '£50', priceMax: '£90',
    tags: ['personal trainer', 'weight loss', 'strength', 'Hyde Park'],
    instagram: 'marcus.fit.ldn', tiktok: 'marcusfit',
    contactPlatform: 'instagram',
    speakingNative: 'English',
    area: 'Hyde Park', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-11-15').getTime(),
    distanceKm: 1.4, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(-0.005, -0.15),
  },

  // ── Wellness ──────────────────────────────────────────────────────────────
  {
    id: 'cat-wellness-1', userId: 'cat-user-wellness', isSeeded: true,
    displayName: 'Luna', age: 32,
    photoURL: 'https://picsum.photos/seed/cat-wellness/400/500',
    photos: ['https://picsum.photos/seed/cat-wellness/400/500'],
    bio: 'Yoga instructor, sound bath facilitator and mindfulness coach. Weekly classes in Shoreditch and private sessions. Retreats in Glastonbury every summer.',
    lookingFor: 'wellness',
    activityType: 'wellness', activities: ['wellness', 'yoga'],
    brandName: 'Luna Wellness', tradeRole: 'selling',
    priceMin: '£20', priceMax: '£120',
    tags: ['yoga', 'sound bath', 'mindfulness', 'meditation', 'retreats'],
    instagram: 'lunawellness.ldn', website: 'https://lunawellness.co.uk',
    contactPlatform: 'instagram',
    speakingNative: 'Spanish', speakingSecond: 'English',
    area: 'Shoreditch', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-01-20').getTime(),
    distanceKm: 1.8, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.03, 0.07),
  },

  // ── Catering ──────────────────────────────────────────────────────────────
  {
    id: 'cat-catering-1', userId: 'cat-user-catering', isSeeded: true,
    displayName: 'Olu', age: 41,
    photoURL: 'https://picsum.photos/seed/cat-catering/400/500',
    photos: ['https://picsum.photos/seed/cat-catering/400/500'],
    bio: 'West African catering for events — suya, jollof, puff puff, pepper soup. Weddings, corporate events and private dining. Minimum 20 guests.',
    lookingFor: 'catering',
    activityType: 'food', activities: ['food'],
    brandName: 'Olu\'s Kitchen', tradeRole: 'selling',
    priceMin: '£18pp', priceMax: '£45pp',
    tags: ['catering', 'west african', 'jollof rice', 'event catering', 'weddings'],
    instagram: 'oluskitchenldn', facebook: 'OlusKitchenLondon',
    contactPlatform: 'whatsapp',
    speakingNative: 'Yoruba', speakingSecond: 'English',
    area: 'Lewisham', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-07-05').getTime(),
    distanceKm: 5.8, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'pro',
    ..._LDN(-0.07, 0.04),
  },

  // ── Restaurant / Food & Drink ─────────────────────────────────────────────
  {
    id: 'cat-restaurant-1', userId: 'cat-user-restaurant', isSeeded: true,
    displayName: 'Nikos', age: 45,
    photoURL: 'https://picsum.photos/seed/cat-restaurant/400/500',
    photos: ['https://picsum.photos/seed/cat-restaurant/400/500'],
    bio: 'Owner of a Greek taverna in Islington — homemade moussaka, fresh octopus and proper retsina. Walk-ins welcome or book a table via Indoo.',
    lookingFor: 'restaurant',
    activityType: 'food', activities: ['food', 'drinks'],
    brandName: 'Nikos Taverna', tradeRole: 'selling', cuisineType: 'greek',
    priceMin: '£22 mains', priceMax: '£65 set menu',
    tags: ['greek food', 'taverna', 'islington', 'dine in', 'date night'],
    instagram: 'nikostaverna', website: 'https://nikostaverna.co.uk',
    contactPlatform: 'phone',
    speakingNative: 'Greek', speakingSecond: 'English',
    area: 'Islington', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-04-18').getTime(),
    distanceKm: 2.3, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.04, -0.01),
  },

  // ── Creative ──────────────────────────────────────────────────────────────
  {
    id: 'cat-creative-1', userId: 'cat-user-creative', isSeeded: true,
    displayName: 'Ines', age: 27,
    photoURL: 'https://picsum.photos/seed/cat-creative/400/500',
    photos: ['https://picsum.photos/seed/cat-creative/400/500'],
    bio: 'Brand designer and illustrator. I build visual identities for small businesses — logo, colour, type, packaging. 5 years freelancing, 80+ clients.',
    lookingFor: 'creative',
    activityType: 'design', activities: ['design', 'branding'],
    brandName: 'Ines Creative', tradeRole: 'selling',
    priceMin: '£350', priceMax: '£2,500',
    tags: ['brand design', 'logo', 'illustration', 'packaging', 'freelance'],
    instagram: 'ines.creative', website: 'https://inescreative.com',
    contactPlatform: 'instagram',
    speakingNative: 'Portuguese', speakingSecond: 'English',
    area: 'Dalston', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-12-10').getTime(),
    distanceKm: 2.9, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(0.05, 0.07),
  },

  // ── Content Creator ───────────────────────────────────────────────────────
  {
    id: 'cat-content-creator-1', userId: 'cat-user-contentcreator', isSeeded: true,
    displayName: 'Bea', age: 24,
    photoURL: 'https://picsum.photos/seed/cat-content-creator/400/500',
    photos: ['https://picsum.photos/seed/cat-content-creator/400/500'],
    bio: 'Food & lifestyle content creator — 180k on TikTok, 42k on Instagram. I work with food brands, restaurants and lifestyle products. Brand deals from £500.',
    lookingFor: 'content_creator',
    activityType: 'content', activities: ['content', 'food'],
    brandName: 'Bea Creates', tradeRole: 'selling',
    priceMin: '£500', priceMax: '£5,000',
    tags: ['tiktok', 'instagram', 'food content', 'brand deals', 'ugc'],
    tiktok: 'beacreates', instagram: 'beacreates',
    contactPlatform: 'instagram',
    speakingNative: 'English',
    area: 'Hackney', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-02-14').getTime(),
    distanceKm: 2.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'pro',
    ..._LDN(0.04, 0.10),
  },

  // ── Photography ───────────────────────────────────────────────────────────
  {
    id: 'cat-photography-1', userId: 'cat-user-photography', isSeeded: true,
    displayName: 'Kai', age: 29,
    photoURL: 'https://picsum.photos/seed/cat-photography/400/500',
    photos: ['https://picsum.photos/seed/cat-photography/400/500'],
    bio: 'Freelance photographer for portraits, events and brand shoots. Based in East London. Fully edited digital delivery within 48 hours. Reel add-on available.',
    lookingFor: 'photography',
    activityType: 'photography', activities: ['photography'],
    brandName: 'Kai Shoots', tradeRole: 'selling', shopType: 'services',
    priceMin: '£150', priceMax: '£950',
    tags: ['photography', 'portraits', 'events', 'brand shoot', 'east london'],
    instagram: 'kai.shoots.ldn', website: 'https://kaishoots.com',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'Japanese',
    area: 'Bethnal Green', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-09-22').getTime(),
    distanceKm: 1.7, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(0.02, 0.08),
  },

  // ── Music ─────────────────────────────────────────────────────────────────
  {
    id: 'cat-music-1', userId: 'cat-user-music', isSeeded: true,
    displayName: 'Dani', age: 26,
    photoURL: 'https://picsum.photos/seed/cat-music/400/500',
    photos: ['https://picsum.photos/seed/cat-music/400/500'],
    bio: 'Session musician and music producer. Piano, keys and synth. I produce R&B, lo-fi and soul. Open to collaborations, live sessions and recording credits.',
    lookingFor: 'music',
    activityType: 'music', activities: ['music'],
    brandName: 'Dani Sounds', tradeRole: 'selling',
    priceMin: '£80', priceMax: '£500',
    tags: ['music producer', 'session musician', 'r&b', 'lo-fi', 'piano'],
    instagram: 'dani.sounds', tiktok: 'danisounds',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'Spanish',
    area: 'Brixton', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-01-03').getTime(),
    distanceKm: 3.2, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(-0.04, -0.02),
  },

  // ── Professional Services ─────────────────────────────────────────────────
  {
    id: 'cat-professional-1', userId: 'cat-user-professional', isSeeded: true,
    displayName: 'Rachel', age: 40,
    photoURL: 'https://picsum.photos/seed/cat-professional/400/500',
    photos: ['https://picsum.photos/seed/cat-professional/400/500'],
    bio: 'Chartered accountant and tax advisor for freelancers and small businesses. Annual accounts, VAT returns and HMRC investigations. Free 30-min call.',
    lookingFor: 'professional',
    activityType: 'business', activities: ['business'],
    brandName: 'Rachel & Co Accountants', tradeRole: 'selling',
    priceMin: '£120', priceMax: '£850/yr',
    tags: ['accountant', 'tax', 'VAT', 'freelancer accounts', 'HMRC'],
    website: 'https://rachelandco.co.uk', linkedin: 'rachel-and-co',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'City of London', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-06-01').getTime(),
    distanceKm: 0.8, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.01, 0.02),
  },

  // ── Legal ─────────────────────────────────────────────────────────────────
  {
    id: 'cat-legal-1', userId: 'cat-user-legal', isSeeded: true,
    displayName: 'James', age: 37,
    photoURL: 'https://picsum.photos/seed/cat-legal/400/500',
    photos: ['https://picsum.photos/seed/cat-legal/400/500'],
    bio: 'Solicitor specialising in employment law and tenancy disputes. Fixed fees, no hidden costs. Over 200 cases settled. Free initial 20-min consultation.',
    lookingFor: 'legal',
    activityType: 'legal', activities: ['legal'],
    brandName: 'James Clarke Solicitors', tradeRole: 'selling',
    priceMin: '£180', priceMax: '£POA',
    tags: ['solicitor', 'employment law', 'tenancy dispute', 'fixed fee'],
    website: 'https://jamesclarke.law', linkedin: 'james-clarke-solicitor',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'Holborn', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-05-14').getTime(),
    distanceKm: 0.6, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.01, -0.02),
  },

  // ── Technology ────────────────────────────────────────────────────────────
  {
    id: 'cat-technology-1', userId: 'cat-user-technology', isSeeded: true,
    displayName: 'Arjun', age: 29,
    photoURL: 'https://picsum.photos/seed/cat-technology/400/500',
    photos: ['https://picsum.photos/seed/cat-technology/400/500'],
    bio: 'Full-stack developer building web and mobile apps for startups. React, Node, Supabase. MVP in 6 weeks guaranteed. Happy to NDA. Portfolio on request.',
    lookingFor: 'technology',
    activityType: 'tech', activities: ['tech'],
    brandName: 'Arjun Dev', tradeRole: 'selling',
    priceMin: '£450/day', priceMax: '£POA',
    tags: ['web dev', 'mobile app', 'react', 'startup', 'MVP'],
    instagram: 'arjun.dev', website: 'https://arjundev.io',
    contactPlatform: 'telegram',
    speakingNative: 'English', speakingSecond: 'Hindi',
    area: 'Shoreditch', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-02-01').getTime(),
    distanceKm: 1.3, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(0.03, 0.05),
  },

  // ── Education ─────────────────────────────────────────────────────────────
  {
    id: 'cat-education-1', userId: 'cat-user-education', isSeeded: true,
    displayName: 'Amara', age: 35,
    photoURL: 'https://picsum.photos/seed/cat-education/400/500',
    photos: ['https://picsum.photos/seed/cat-education/400/500'],
    bio: 'Secondary school teacher and private tutor. Maths, Physics and Chemistry. GCSE and A-Level specialist. Small groups (max 4) or 1-to-1. CRB checked.',
    lookingFor: 'education',
    activityType: 'education', activities: ['education'],
    brandName: 'Amara Tutors', tradeRole: 'selling',
    priceMin: '£40/hr', priceMax: '£65/hr',
    tags: ['tutor', 'maths', 'physics', 'GCSE', 'A-level'],
    facebook: 'AmaraTutorsLondon',
    contactPlatform: 'whatsapp',
    speakingNative: 'French', speakingSecond: 'English',
    area: 'Streatham', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-09-01').getTime(),
    distanceKm: 5.4, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(-0.08, -0.01),
  },

  // ── Coaching ──────────────────────────────────────────────────────────────
  {
    id: 'cat-coaching-1', userId: 'cat-user-coaching', isSeeded: true,
    displayName: 'Simone', age: 41,
    photoURL: 'https://picsum.photos/seed/cat-coaching/400/500',
    photos: ['https://picsum.photos/seed/cat-coaching/400/500'],
    bio: 'ICF-accredited life and career coach. I help people change careers, overcome burnout and build confidence. 12-week programmes or single sessions.',
    lookingFor: 'coaching',
    activityType: 'coaching', activities: ['coaching'],
    brandName: 'Simone Coaching', tradeRole: 'selling',
    priceMin: '£90', priceMax: '£1,200/programme',
    tags: ['life coach', 'career change', 'burnout', 'confidence', 'ICF'],
    instagram: 'simone.coaching', website: 'https://simonecoaching.co.uk',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'French',
    area: 'Richmond', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-10-11').getTime(),
    distanceKm: 8.2, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'pro',
    ..._LDN(-0.05, -0.20),
  },

  // ── Hiring ────────────────────────────────────────────────────────────────
  {
    id: 'cat-hiring-1', userId: 'cat-user-hiring', isSeeded: true,
    displayName: 'Tom', age: 33,
    photoURL: 'https://picsum.photos/seed/cat-hiring/400/500',
    photos: ['https://picsum.photos/seed/cat-hiring/400/500'],
    bio: 'Tech recruiter placing engineers, designers and PMs at London startups. No fee to candidates. I currently have 14 open roles across Series A–C companies.',
    lookingFor: 'hiring',
    activityType: 'business', activities: ['business'],
    brandName: 'Tom Recruit', tradeRole: 'both',
    priceMin: 'No fee', priceMax: 'Employer-paid',
    tags: ['tech jobs', 'startup jobs', 'engineering roles', 'product roles'],
    linkedin: 'tom-recruit-ldn', instagram: 'tomrecruitldn',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'Old Street', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-03-01').getTime(),
    distanceKm: 1.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.04, 0.04),
  },

  // ── Freelance ─────────────────────────────────────────────────────────────
  {
    id: 'cat-freelance-1', userId: 'cat-user-freelance', isSeeded: true,
    displayName: 'Sasha', age: 28,
    photoURL: 'https://picsum.photos/seed/cat-freelance/400/500',
    photos: ['https://picsum.photos/seed/cat-freelance/400/500'],
    bio: 'Freelance copywriter and content strategist. I write for fintech, health and lifestyle brands. Fast turnaround, SEO-optimised. Published in Forbes and Wired.',
    lookingFor: 'freelance',
    activityType: 'writing', activities: ['writing', 'content'],
    brandName: 'Sasha Writes', tradeRole: 'selling',
    priceMin: '£150', priceMax: '£1,800/project',
    tags: ['copywriting', 'content strategy', 'SEO', 'fintech', 'lifestyle'],
    website: 'https://sashawrites.com', linkedin: 'sasha-writes',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'Farringdon', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2025-11-25').getTime(),
    distanceKm: 0.7, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.01, -0.03),
  },

  // ── Social / Meet New People ───────────────────────────────────────────────
  {
    id: 'cat-meet-new-1', userId: 'cat-user-meetnew', isSeeded: true,
    displayName: 'Felix', age: 27,
    photoURL: 'https://picsum.photos/seed/cat-meet-new/400/500',
    photos: ['https://picsum.photos/seed/cat-meet-new/400/500'],
    bio: 'New to London from Berlin. Looking to meet genuine people — not just another WhatsApp group that never plans anything. Coffee or evening drinks?',
    lookingFor: 'meet_new',
    activityType: 'hangout', activities: ['hangout', 'coffee', 'drinks'],
    speakingNative: 'German', speakingSecond: 'English',
    area: 'Angel', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-03-20').getTime(),
    distanceKm: 1.9, expiresAtMs: now + 6 * 60 * 60 * 1000,
    ..._LDN(0.03, -0.005),
  },

  // ── Friendship ────────────────────────────────────────────────────────────
  {
    id: 'cat-friendship-1', userId: 'cat-user-friendship', isSeeded: true,
    displayName: 'Kezia', age: 30,
    photoURL: 'https://picsum.photos/seed/cat-friendship/400/500',
    photos: ['https://picsum.photos/seed/cat-friendship/400/500'],
    bio: 'Just moved back to London after 3 years in Sydney. Looking for proper friends, not followers. Love hiking, board games and independent cinema.',
    lookingFor: 'friendship',
    activityType: 'hangout', activities: ['hangout', 'walk', 'cinema'],
    speakingNative: 'English',
    area: 'Stoke Newington', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-03-15').getTime(),
    distanceKm: 3.5, expiresAtMs: now + 6 * 60 * 60 * 1000,
    ..._LDN(0.06, 0.02),
  },

  // ── Sports / Active ───────────────────────────────────────────────────────
  {
    id: 'cat-sports-1', userId: 'cat-user-sports', isSeeded: true,
    displayName: 'Ravi', age: 25,
    photoURL: 'https://picsum.photos/seed/cat-sports/400/500',
    photos: ['https://picsum.photos/seed/cat-sports/400/500'],
    bio: 'Looking for 5-a-side teammates and running partners. I run 5k every morning in Victoria Park. Also up for tennis, padel and swimming. Competitive but friendly.',
    lookingFor: 'sports',
    activityType: 'sports', activities: ['sports', 'run', 'tennis'],
    speakingNative: 'English', speakingSecond: 'Tamil',
    area: 'Victoria Park', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-02-28').getTime(),
    distanceKm: 2.7, expiresAtMs: now + 6 * 60 * 60 * 1000,
    ..._LDN(0.05, 0.11),
  },

  // ── Gaming ────────────────────────────────────────────────────────────────
  {
    id: 'cat-gaming-1', userId: 'cat-user-gaming', isSeeded: true,
    displayName: 'Ellie', age: 23,
    photoURL: 'https://picsum.photos/seed/cat-gaming/400/500',
    photos: ['https://picsum.photos/seed/cat-gaming/400/500'],
    bio: 'Gamer girl — PC, PS5 and board games. Looking for chill people to game with IRL or online. I co-run a board game night every other Thursday in Soho.',
    lookingFor: 'gaming',
    activityType: 'gaming', activities: ['gaming', 'hangout'],
    speakingNative: 'English',
    area: 'Soho', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out', userJoinedAt: new Date('2026-03-10').getTime(),
    distanceKm: 0.5, expiresAtMs: now + 6 * 60 * 60 * 1000,
    ..._LDN(0.01, -0.01),
  },

]

// ─────────────────────────────────────────────────────────────────────────────
// DEMO_BUSINESS_SELLERS — mock business profiles for ShopSearchScreen
// ─────────────────────────────────────────────────────────────────────────────
