import { offset, now, _isUKLateNight, tonight, tomorrow } from "./mockHelpers"

export const DEMO_USER = {
  uid: 'demo-me',
  displayName: 'You',
  photoURL: null,
  phoneNumber: null,
  email: 'demo@indoo.id',
}

// Sessions extracted from mockData.js
const _ACTIVE_SESSIONS = [
  {
    id: 'demo-session-1',
    userId: 'demo-user-1',
    displayName: 'Sophie', age: 27,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk1.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk1.png','https://ik.imagekit.io/nepgaxllc/uk3.png','https://ik.imagekit.io/nepgaxllc/uk5.png','https://ik.imagekit.io/nepgaxllc/uk7.png'],
    gender: 'female',
    bio: 'Love a good cocktail bar and terrible karaoke 🎤',
    activityType: 'cocktails',
    activities: ['cocktails', 'food', 'hangout'],
    lookingFor: 'Dating',
    area: 'Soho', city: 'London',
    status: 'active', venueId: 'venue-soho-bar', tier: 'vip',
    distanceKm: 0.3,
    expiresAtMs: now + 45 * 60 * 1000, startedAtMs: now - 15 * 60 * 1000,
    lat: 51.5135, lng: -0.1322,
  },
  {
    id: 'demo-session-2',
    userId: 'demo-user-2',
    displayName: 'Emma', age: 25,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk3.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk3.png','https://ik.imagekit.io/nepgaxllc/uk6.png','https://ik.imagekit.io/nepgaxllc/uk9.png'],
    gender: 'female',
    bio: 'Yoga mornings, wine evenings. Looking for good company ✨',
    activityType: 'wine',
    activities: ['wine', 'coffee', 'walk'],
    lookingFor: 'Dating',
    area: 'Covent Garden', city: 'London',
    status: 'active', venueId: 'venue-soho-bar', tier: 'pro',
    distanceKm: 0.6,
    expiresAtMs: now + 30 * 60 * 1000, startedAtMs: now - 20 * 60 * 1000,
    lat: 51.5131, lng: -0.1318,
  },
  {
    id: 'demo-session-3',
    userId: 'demo-user-3',
    displayName: 'Charlotte', age: 29,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk4.png',
    gender: 'female',
    bio: 'Foodie and part-time art gallery wanderer 🍷',
    activityType: 'pizza',
    activities: ['pizza', 'wine', 'cinema'],
    lookingFor: 'Dating',
    area: 'Fitzrovia', city: 'London',
    status: 'active', venueId: 'venue-fitz-bistro',
    distanceKm: 1.1,
    expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 10 * 60 * 1000,
    lat: 51.5198, lng: -0.1359,
  },
  {
    id: 'demo-session-4',
    userId: 'demo-user-4',
    displayName: 'Olivia', age: 24,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk5.png',
    gender: 'female',
    bio: 'Up for spontaneous plans — life\'s too short to stay in 🌙',
    activityType: 'bowling',
    activities: ['bowling', 'fastfood', 'hangout'],
    lookingFor: 'Dating',
    area: 'Shoreditch', city: 'London',
    status: 'active', venueId: 'venue-hyde-pub',
    distanceKm: 2.4,
    expiresAtMs: now + 55 * 60 * 1000, startedAtMs: now - 5 * 60 * 1000,
    lat: 51.5220, lng: -0.0760,
  },
  {
    id: 'demo-session-5',
    userId: 'demo-user-5',
    displayName: 'Isabelle', age: 31,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk6.png',
    gender: 'female',
    bio: 'Coffee snob by day, gin lover by night ☕',
    activityType: 'cinema',
    activities: ['cinema', 'cocktails', 'coffee'],
    lookingFor: 'Dating',
    area: 'Hyde Park', city: 'London',
    status: 'active', venueId: 'venue-bloomsbury-pub',
    distanceKm: 1.8,
    expiresAtMs: now + 20 * 60 * 1000, startedAtMs: now - 40 * 60 * 1000,
    lat: 51.5064, lng: -0.1732,
  },
  {
    id: 'demo-session-6',
    userId: 'demo-user-6',
    displayName: 'Amelia', age: 28,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk8.png',
    gender: 'female',
    bio: 'Brunch enthusiast. Will judge you by your coffee order ☕',
    activityType: 'fastfood',
    activities: ['fastfood', 'cocktails', 'coffee'],
    lookingFor: 'Dating',
    area: 'Camden', city: 'London',
    status: 'active', venueId: 'venue-soho-bar', tier: 'boost',
    distanceKm: 3.2,
    expiresAtMs: now + 75 * 60 * 1000, startedAtMs: now - 5 * 60 * 1000,
    lat: 51.5390, lng: -0.1426,
  },
  {
    id: 'demo-session-8',
    userId: 'demo-user-10',
    displayName: 'Mia', age: 29,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk7.png',
    gender: 'female',
    bio: 'Wine and pintxos kind of evening 🍷',
    activityType: 'wine',
    activities: ['wine', 'pizza'],
    lookingFor: 'Dating',
    area: 'Fitzrovia', city: 'London',
    status: 'active', venueId: 'partner-barrica', distanceKm: 0.9,
    expiresAtMs: now + 45 * 60 * 1000, startedAtMs: now - 20 * 60 * 1000,
    lat: 51.5196, lng: -0.1357,
  },
]

// Hide active sessions after midnight UK time
export const DEMO_SESSIONS = _isUKLateNight ? [] : _ACTIVE_SESSIONS

// Scheduled sessions — "I'm Out Later"
// scheduledFor = ms timestamp when they go live

export const DEMO_SCHEDULED_SESSIONS = [
  {
    id: 'demo-sched-1', userId: 'demo-user-7',
    displayName: 'Poppy', age: 26,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk9.png',
    gender: 'female',
    bio: 'Looking for someone to explore the city with 🗺️',
    activityType: 'drinks',
    activities: ['drinks', 'food', 'hangout'],
    lookingFor: 'Dating',
    area: 'Soho', city: 'London',
    distanceKm: 0.7,
    status: 'scheduled', scheduledFor: tonight(20, 0),
    expiresAtMs: tonight(20, 0) + 120 * 60 * 1000, startedAtMs: null,
    ...offset(300, 700),
  },
  {
    id: 'demo-sched-2', userId: 'demo-user-8',
    displayName: 'Grace', age: 30,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk10.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk10.png', 'https://ik.imagekit.io/nepgaxllc/Untitleddfsdf.png', 'https://ik.imagekit.io/nepgaxllc/Untitleddfsdfss.png', 'https://ik.imagekit.io/nepgaxllc/Untitleddfsdfssxczxcsss.png'],
    gender: 'female',
    bio: 'Film nights and good restaurants. Simple pleasures 🎬',
    activityType: 'walk',
    activities: ['walk', 'hiking', 'culture'],
    lookingFor: 'Dating',
    area: 'Shoreditch', city: 'London',
    distanceKm: 1.4,
    status: 'scheduled', scheduledFor: tonight(19, 30),
    expiresAtMs: tonight(19, 30) + 90 * 60 * 1000, startedAtMs: null,
    ...offset(400, 800),
  },
  {
    id: 'demo-sched-3', userId: 'demo-user-9',
    displayName: 'Harriet', age: 24,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk3.png',
    gender: 'female',
    bio: 'Cinema then cocktails — best evening ever 🍸',
    activityType: 'culture',
    activities: ['culture', 'coffee', 'drinks'],
    lookingFor: 'Dating',
    area: 'Leicester Sq', city: 'London',
    distanceKm: 2.2,
    status: 'scheduled', scheduledFor: tomorrow(18, 0),
    expiresAtMs: tomorrow(18, 0) + 150 * 60 * 1000, startedAtMs: null,
    ...offset(200, 500),
  },
]

export const DEMO_INVITE_OUT_SESSIONS = [
  {
    id: 'demo-invite-2', userId: 'demo-user-11',
    isSeeded: true,
    userJoinedAt: new Date('2025-10-03').getTime(),
    displayName: 'Daisy', age: 29,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk4.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk4.png', 'https://ik.imagekit.io/nepgaxllc/bbbffdcc.png', 'https://ik.imagekit.io/nepgaxllc/bbbffdccss.png'],
    gender: 'female',
    bio: 'Fun, kind, and a little bit cheeky. I love good conversations, late night laughs, and spontaneous plans. Into coffee, music, and exploring new places. Looking for someone genuine who can make me smile and isn\'t afraid to be themselves. Bonus points if you can make me laugh or recommend great food spots nearby!',
    activityType: 'food',
    activities: ['food', 'drinks', 'culture'],
    lookingFor: 'dating',
    relationshipGoal: 'open',
    starSign: 'Libra',
    speakingNative: 'English',
    speakingSecond: 'French',
    area: 'Soho', city: 'London',
    distanceKm: 1.9,
    status: 'invite_out',
    message: 'Looking for somewhere good to eat tonight',
    ...offset(200, 600),
  },
  {
    id: 'demo-invite-3', userId: 'demo-user-12',
    isSeeded: true,
    userJoinedAt: new Date('2025-11-20').getTime(),
    displayName: 'Freya', age: 24,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk6.png',
    gender: 'female',
    bio: 'Morning runs, afternoon coffee, evening adventures ☕',
    activityType: 'coffee',
    activities: ['coffee', 'walk', 'hangout'],
    lookingFor: 'Dating',
    area: 'Covent Garden', city: 'London',
    distanceKm: 0.3,
    status: 'invite_out',
    message: 'Free this afternoon if anyone wants to explore',
    ...offset(400, 800),
  },
  {
    id: 'demo-invite-4', userId: 'demo-user-13',
    isSeeded: true,
    userJoinedAt: new Date('2026-01-07').getTime(),
    displayName: 'Imogen', age: 32,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk9.png',
    gender: 'female',
    bio: 'Park walks and good conversation — my kind of date 🌿',
    activityType: 'walk',
    activities: ['walk', 'coffee', 'food'],
    lookingFor: 'Dating',
    area: 'Hyde Park', city: 'London',
    distanceKm: 2.8,
    status: 'invite_out',
    message: 'Up for a walk if anyone is around',
    ...offset(500, 900),
  },
  {
    id: 'demo-invite-5', userId: 'demo-user-14',
    isSeeded: true,
    userJoinedAt: new Date('2026-02-19').getTime(),
    displayName: 'Rosie', age: 27,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk10.png',
    gender: 'female',
    bio: 'Gin & tonic in hand, ready for a great night 🥂',
    activityType: 'drinks',
    activities: ['drinks', 'food', 'hangout'],
    lookingFor: 'Dating',
    distanceKm: 1.1,
    area: 'Camden', city: 'London',
    status: 'invite_out',
    message: 'Anyone else out in Camden tonight?',
    ...offset(300, 650),
  },
]

// ── Dating bubble screen mock profiles ───────────────────────────────────────

export const DEMO_DATING_BUBBLES = [
  {
    id: 'dating-bubble-1', userId: 'dating-user-1', isSeeded: true,
    displayName: 'Sophia', dob: '1998-03-14',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk4.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk4.png'],
    lookingFor: 'dating', moodLight: 'pink',
    status: 'active', city: 'London', area: 'Soho',
  },
  {
    id: 'dating-bubble-2', userId: 'dating-user-2', isSeeded: true,
    displayName: 'Freya', dob: '2000-07-22',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk6.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk6.png'],
    lookingFor: 'dating', moodLight: 'cool',
    status: 'active', city: 'London', area: 'Shoreditch',
  },
  {
    id: 'dating-bubble-3', userId: 'dating-user-3', isSeeded: true,
    displayName: 'Imogen', dob: '1993-11-05',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk9.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk9.png'],
    lookingFor: 'marriage', moodLight: 'warm',
    status: 'active', city: 'London', area: 'Hyde Park',
  },
  {
    id: 'dating-bubble-4', userId: 'dating-user-4', isSeeded: true,
    displayName: 'Rosie', dob: '1996-05-30',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk10.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk10.png'],
    lookingFor: 'date_night', moodLight: 'pink',
    status: 'active', city: 'London', area: 'Camden',
  },
  {
    id: 'dating-bubble-5', userId: 'dating-user-5', isSeeded: true,
    displayName: 'Daisy', dob: '1997-09-18',
    photoURL: 'https://ik.imagekit.io/nepgaxllc/bbbffdcc.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/bbbffdcc.png'],
    lookingFor: 'travel', moodLight: 'cool',
    status: 'active', city: 'London', area: 'Covent Garden',
  },
]

// ── Indonesian maker / handmade sessions — used for city search demo ──────────
