// Shared payment gateway + Indonesian bank definitions for all 8 customer-facing apps.
// Edit ONCE here — all consuming apps pick up the change automatically.
// Vendors connect their OWN gateway accounts; StreetLocal never touches their funds.

export const SUPPORTED_GATEWAYS = [
  {
    id: 'stripe',
    name: 'Stripe',
    tagline: 'Cards · Apple Pay · Google Pay · Klarna',
    color: '#635BFF',
    logoUrl: 'https://cdn.simpleicons.org/stripe/white',
    countryFlags: '🇺🇸 🇬🇧 🇨🇦 🇦🇺 🇩🇪 🇫🇷 🇸🇬 🇯🇵 🇭🇰 🇲🇾 🇹🇭 🇲🇽 🇧🇷',
    countryCount: '46 countries',
    fees: '2.9% + fixed fee · 0.5% extra for non-US cards',
    bestFor: 'International vendors · global reach',
    method: 'oauth-or-keys',
    fields: [
      { key: 'publishableKey', label: 'Publishable Key', placeholder: 'pk_test_... or pk_live_...', type: 'text', required: true },
      { key: 'secretKey', label: 'Secret Key', placeholder: 'sk_test_... or sk_live_...', type: 'password', required: true, secret: true },
      { key: 'webhookSecret', label: 'Webhook signing secret (optional)', placeholder: 'whsec_...', type: 'password', secret: true },
    ],
    docUrl: 'https://dashboard.stripe.com/apikeys',
    setupSteps: ['Sign up free at stripe.com', 'Complete business verification (KYC)', 'Copy your API keys from Dashboard → Developers → API keys', 'Paste them here'],
  },
  {
    id: 'midtrans',
    name: 'Midtrans',
    tagline: 'GoPay · OVO · DANA · ShopeePay · cards · bank',
    color: '#1A6FE8',
    logoUrl: 'https://midtrans.com/blog/wp-content/uploads/2018/05/cropped-Midtrans-website-fav-32x32.png',
    countryFlags: '🇮🇩',
    countryCount: 'Indonesia only',
    fees: '~2.5% per transaction · varies by method',
    bestFor: 'Indonesian vendors · local customers',
    method: 'api-keys',
    fields: [
      { key: 'serverKey', label: 'Server Key', placeholder: 'Mid-server-...', type: 'password', required: true, secret: true },
      { key: 'clientKey', label: 'Client Key', placeholder: 'Mid-client-...', type: 'text', required: true },
      { key: 'merchantId', label: 'Merchant ID', placeholder: 'M01234', type: 'text' },
    ],
    docUrl: 'https://dashboard.midtrans.com/settings/config_info',
    setupSteps: ['Register at midtrans.com', 'Complete merchant verification', 'Settings → Access Keys', 'Copy Server Key + Client Key here'],
  },
  {
    id: 'xendit',
    name: 'Xendit',
    tagline: 'Cards · e-wallets · virtual accounts · QRIS',
    color: '#EB5E28',
    logoUrl: 'https://cdn.simpleicons.org/xendit/white',
    countryFlags: '🇮🇩 🇵🇭 🇲🇾 🇸🇬 🇹🇭 🇻🇳',
    countryCount: '6 SEA countries',
    fees: '~2.5% · multi-currency',
    bestFor: 'Regional SEA sellers',
    method: 'api-keys',
    fields: [
      { key: 'secretKey', label: 'Secret API Key', placeholder: 'xnd_development_... or xnd_production_...', type: 'password', required: true, secret: true },
      { key: 'publicKey', label: 'Public Key (optional)', placeholder: 'xnd_public_...', type: 'text' },
    ],
    docUrl: 'https://dashboard.xendit.co/settings/developers#api-keys',
    setupSteps: ['Sign up at xendit.co', 'Complete onboarding + KYC', 'Settings → Developers → API Keys', 'Generate and paste your Secret Key'],
  },
  {
    id: 'paypal',
    name: 'PayPal',
    tagline: 'Cards + PayPal balance · world\'s most familiar',
    color: '#0070BA',
    logoUrl: 'https://cdn.simpleicons.org/paypal/white',
    countryFlags: '🇺🇸 🇬🇧 🇨🇦 🇦🇺 🇪🇺 🇮🇳 🇮🇩 🇲🇾 🇸🇬 🇵🇭 🇯🇵 🇲🇽 🇧🇷',
    countryCount: '200+ countries',
    fees: '3.49% + fixed fee · varies by country',
    bestFor: 'International customers · PayPal-preferring buyers',
    method: 'oauth-or-email',
    fields: [
      { key: 'merchantEmail', label: 'PayPal Business Email', placeholder: 'shop@example.com', type: 'email', required: true },
      { key: 'clientId', label: 'REST API Client ID', placeholder: 'AeA1QIZX...', type: 'text' },
      { key: 'secret', label: 'REST API Secret', placeholder: '••••••••', type: 'password', secret: true },
    ],
    docUrl: 'https://developer.paypal.com/dashboard/applications',
    setupSteps: ['Upgrade to PayPal Business at paypal.com', 'Create REST API app at developer.paypal.com', 'Copy Client ID + Secret', 'Paste here'],
  },
  {
    id: 'braintree',
    name: 'Braintree',
    tagline: 'Cards + PayPal + Venmo · PayPal-owned',
    color: '#00ADEF',
    logoUrl: 'https://cdn.simpleicons.org/braintree/white',
    countryFlags: '🇺🇸 🇬🇧 🇨🇦 🇦🇺 🇸🇬 🇲🇾 🇪🇺 🇭🇰',
    countryCount: '45+ countries',
    fees: '2.59% + $0.49 (US) · varies by region',
    bestFor: 'Vendors who want cards + Venmo + PayPal in one integration',
    method: 'api-keys',
    fields: [
      { key: 'merchantId', label: 'Merchant ID', placeholder: 'xxxxxxxxxxxxxxxx', type: 'text', required: true },
      { key: 'publicKey', label: 'Public Key', placeholder: 'xxxxxxxxxxxxxxxx', type: 'text', required: true },
      { key: 'privateKey', label: 'Private Key', placeholder: '••••', type: 'password', required: true, secret: true },
    ],
    docUrl: 'https://www.braintreepayments.com/sandbox',
    setupSteps: ['Sign up at braintreepayments.com', 'Complete business verification', 'Account → Settings → API Keys', 'Generate and paste your Merchant ID + keys'],
  },
  {
    id: 'checkout-com',
    name: 'Checkout.com',
    tagline: 'Modern API · global cards + alternative methods',
    color: '#1A1F36',
    logoUrl: null,
    countryFlags: '🇬🇧 🇫🇷 🇩🇪 🇪🇸 🇮🇹 🇳🇱 🇸🇬 🇦🇺 🇦🇪 🇸🇦',
    countryCount: '150+ currencies · global',
    fees: 'Custom · ~1.95% + $0.20 typical',
    bestFor: 'SaaS · subscriptions · EMEA/APAC merchants',
    method: 'api-keys',
    fields: [
      { key: 'publicKey', label: 'Public Key', placeholder: 'pk_sbox_... or pk_...', type: 'text', required: true },
      { key: 'secretKey', label: 'Secret Key', placeholder: 'sk_sbox_... or sk_...', type: 'password', required: true, secret: true },
    ],
    docUrl: 'https://dashboard.checkout.com/developers/keys',
    setupSteps: ['Apply at checkout.com (KYC required)', 'Wait for approval (3–7 days typical)', 'Dashboard → Developers → Keys', 'Copy Public + Secret keys'],
  },
  {
    id: 'authorize-net',
    name: 'Authorize.net',
    tagline: 'Veteran US gateway · Visa-owned',
    color: '#0066B2',
    logoUrl: null,
    countryFlags: '🇺🇸 🇨🇦 🇬🇧 🇦🇺',
    countryCount: '4 countries',
    fees: '2.9% + $0.30 + $25/mo gateway fee',
    bestFor: 'US-based merchants with existing card processor',
    method: 'api-keys',
    fields: [
      { key: 'apiLoginId', label: 'API Login ID', placeholder: '5KP3u95bQpv', type: 'text', required: true },
      { key: 'transactionKey', label: 'Transaction Key', placeholder: '••••', type: 'password', required: true, secret: true },
      { key: 'signatureKey', label: 'Signature Key (for webhooks)', placeholder: '••••', type: 'password', secret: true },
    ],
    docUrl: 'https://account.authorize.net/',
    setupSteps: ['Sign up at authorize.net (US merchant account required)', 'Complete KYC and business verification', 'Account → Settings → API Credentials & Keys', 'Copy API Login ID + Transaction Key'],
  },
  {
    id: 'mollie',
    name: 'Mollie',
    tagline: 'iDEAL · Bancontact · SEPA · cards · easy onboarding',
    color: '#06D6A0',
    logoUrl: null,
    countryFlags: '🇳🇱 🇩🇪 🇫🇷 🇧🇪 🇬🇧 🇮🇹 🇪🇸 🇦🇹 🇨🇭 🇩🇰 🇫🇮 🇳🇴 🇸🇪',
    countryCount: 'Europe · 13 countries',
    fees: '~1.8% + €0.25 (iDEAL: €0.29 fixed)',
    bestFor: 'European vendors · local methods preferred',
    method: 'api-keys',
    fields: [
      { key: 'liveApiKey', label: 'Live API Key', placeholder: 'live_...', type: 'password', required: true, secret: true },
      { key: 'testApiKey', label: 'Test API Key (sandbox)', placeholder: 'test_...', type: 'password', secret: true },
    ],
    docUrl: 'https://my.mollie.com/dashboard/developers/api-keys',
    setupSteps: ['Sign up at mollie.com', 'Complete short business verification (~24h)', 'Dashboard → Developers → API keys', 'Copy your live + test keys'],
  },
  {
    id: '2checkout',
    name: '2Checkout (Verifone)',
    tagline: 'Subscriptions · digital products · global',
    color: '#FF6700',
    logoUrl: null,
    countryFlags: '🌍',
    countryCount: '200+ countries · 100+ currencies',
    fees: '3.5% + $0.35 + monthly fees',
    bestFor: 'SaaS · digital products · subscription billing',
    method: 'api-keys',
    fields: [
      { key: 'merchantCode', label: 'Merchant Code', placeholder: '255000000000', type: 'text', required: true },
      { key: 'secretKey', label: 'Secret Key', placeholder: '••••', type: 'password', required: true, secret: true },
      { key: 'publishableKey', label: 'Publishable Key', placeholder: '••••', type: 'text' },
    ],
    docUrl: 'https://secure.2checkout.com/cpanel/',
    setupSteps: ['Sign up at 2checkout.com (now Verifone)', 'Complete merchant verification', 'Dashboard → Integrations → Webhooks & API', 'Copy Merchant Code + Secret Key'],
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    tagline: 'India\'s #1 · UPI · Cards · NetBanking · Wallets',
    color: '#3395FF',
    logoUrl: 'https://cdn.simpleicons.org/razorpay/white',
    countryFlags: '🇮🇳',
    countryCount: 'India only',
    fees: '2% cards · 0% UPI · 0% NetBanking',
    bestFor: 'Indian merchants · UPI/RuPay focus',
    method: 'api-keys',
    fields: [
      { key: 'keyId', label: 'Key ID', placeholder: 'rzp_test_... or rzp_live_...', type: 'text', required: true },
      { key: 'keySecret', label: 'Key Secret', placeholder: '••••', type: 'password', required: true, secret: true },
    ],
    docUrl: 'https://dashboard.razorpay.com/app/keys',
    setupSteps: ['Sign up at razorpay.com (Indian PAN + bank account required)', 'Complete merchant KYC', 'Dashboard → Account & Settings → API Keys', 'Generate and paste your Key ID + Secret'],
  },
  {
    id: 'hitpay',
    name: 'HitPay',
    tagline: 'SMB-friendly · same-day signup · SG/MY/HK/AU',
    color: '#E62D6E',
    logoUrl: null,
    countryFlags: '🇸🇬 🇲🇾 🇭🇰 🇦🇺',
    countryCount: '4 countries',
    fees: '~3.4% + SGD 0.50 · no monthly fee',
    bestFor: 'SEA small biz · cafes · F&B · fast signup',
    method: 'api-keys',
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: '••••', type: 'password', required: true, secret: true },
      { key: 'salt', label: 'Salt (HMAC verification)', placeholder: '••••', type: 'password', secret: true },
    ],
    docUrl: 'https://dashboard.hitpayapp.com/settings/api-keys',
    setupSteps: ['Sign up at hitpayapp.com (SG business or local address)', 'Complete light KYC (~1 day)', 'Dashboard → Settings → API Keys', 'Generate API Key + Salt'],
  },
  {
    id: 'fomo-pay',
    name: 'FOMO Pay',
    tagline: 'WeChat · AliPay · GrabPay · Asia digital wallets',
    color: '#F0392B',
    logoUrl: null,
    countryFlags: '🇸🇬 🇭🇰 🇲🇾 🇵🇭 🇹🇭',
    countryCount: '5 Asian markets',
    fees: 'Custom · varies by method',
    bestFor: 'Asian merchants · Chinese tourist payment methods',
    method: 'api-keys',
    fields: [
      { key: 'merchantId', label: 'Merchant ID', placeholder: 'M0123456', type: 'text', required: true },
      { key: 'apiKey', label: 'API Key', placeholder: '••••', type: 'password', required: true, secret: true },
      { key: 'signKey', label: 'Sign Key (HMAC)', placeholder: '••••', type: 'password', secret: true },
    ],
    docUrl: 'https://www.fomopay.com/contact',
    setupSteps: ['Contact FOMO Pay sales at fomopay.com', 'Complete merchant onboarding (5–10 business days)', 'Receive Merchant ID + API credentials', 'Paste them here'],
  },
  {
    id: 'rapyd',
    name: 'Rapyd',
    tagline: '900+ local payment methods · global coverage',
    color: '#3A23E0',
    logoUrl: null,
    countryFlags: '🌍',
    countryCount: '100+ countries · 900+ methods',
    fees: 'Custom per method · contact sales',
    bestFor: 'Local payment methods worldwide · emerging markets',
    method: 'api-keys',
    fields: [
      { key: 'accessKey', label: 'Access Key', placeholder: '••••', type: 'text', required: true },
      { key: 'secretKey', label: 'Secret Key', placeholder: '••••', type: 'password', required: true, secret: true },
    ],
    docUrl: 'https://dashboard.rapyd.net/account/api-credentials',
    setupSteps: ['Sign up at rapyd.net (business KYC required)', 'Approval takes 5–10 business days', 'Dashboard → Developers → Credentials', 'Copy Access Key + Secret Key'],
  },
  {
    id: 'adyen',
    name: 'Adyen',
    tagline: 'Enterprise-grade · 250+ payment methods',
    color: '#0ABF53',
    logoUrl: 'https://cdn.simpleicons.org/adyen/white',
    countryFlags: '🌍',
    countryCount: '40+ countries · 150+ currencies',
    fees: 'Custom contract · $0.12 + interchange typical',
    bestFor: 'High-volume merchants (>$1M/yr)',
    tier: 'enterprise',
    method: 'api-keys',
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: 'AQEyhmf...', type: 'password', required: true, secret: true },
      { key: 'merchantAccount', label: 'Merchant Account name', placeholder: 'YourCompanyECOM', type: 'text', required: true },
      { key: 'hmacKey', label: 'HMAC Key (webhook)', placeholder: '••••', type: 'password', secret: true },
      { key: 'clientKey', label: 'Client Key', placeholder: 'live_... or test_...', type: 'text' },
    ],
    docUrl: 'https://ca-test.adyen.com/ca/ca/overview/default.shtml',
    setupSteps: ['Contact Adyen sales (enterprise application)', 'Full enterprise KYC (~30 days)', 'Customer Area → Developers → API Credentials', 'Generate API Key + HMAC + Client Key'],
  },
  {
    id: 'cybersource',
    name: 'CyberSource',
    tagline: 'Visa-owned · enterprise fraud screening',
    color: '#1A5490',
    logoUrl: null,
    countryFlags: '🌍',
    countryCount: '190+ countries',
    fees: 'Custom enterprise contract',
    bestFor: 'Visa-network enterprise · fraud screening priority',
    tier: 'enterprise',
    method: 'api-keys',
    fields: [
      { key: 'merchantId', label: 'Merchant ID', placeholder: 'your-merchant-id', type: 'text', required: true },
      { key: 'apiKeyId', label: 'API Key ID', placeholder: '••••', type: 'text', required: true },
      { key: 'sharedSecret', label: 'Shared Secret Key', placeholder: '••••', type: 'password', required: true, secret: true },
    ],
    docUrl: 'https://ebc2.cybersource.com/',
    setupSteps: ['Apply for CyberSource merchant account (sales contact)', 'Enterprise KYC process (4–8 weeks)', 'Business Center → Key Management', 'Generate REST API key set'],
  },
  {
    id: 'worldpay',
    name: 'Worldpay (FIS)',
    tagline: 'Enterprise · omnichannel · 146 countries',
    color: '#E5251F',
    logoUrl: null,
    countryFlags: '🌍',
    countryCount: '146 countries · 126 currencies',
    fees: 'Custom enterprise contract',
    bestFor: 'High-volume retail · physical + online combined',
    tier: 'enterprise',
    method: 'api-keys',
    fields: [
      { key: 'serviceKey', label: 'Service Key (test/live)', placeholder: 'T_S_... or L_S_...', type: 'password', required: true, secret: true },
      { key: 'clientKey', label: 'Client Key', placeholder: 'T_C_... or L_C_...', type: 'text', required: true },
    ],
    docUrl: 'https://online.worldpay.com/',
    setupSteps: ['Apply for Worldpay/FIS merchant account (sales)', 'Enterprise KYC (~6–12 weeks)', 'Dashboard → Integration → Keys', 'Copy Service Key + Client Key'],
  },
  {
    id: 'ewallet',
    name: 'QRIS / E-Wallet',
    tagline: 'GoPay · OVO · DANA · ShopeePay (direct QR)',
    color: '#22C55E',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Logo_QRIS.svg/240px-Logo_QRIS.svg.png',
    countryFlags: '🇮🇩',
    countryCount: 'Indonesia',
    fees: '0% — customer pays you direct',
    bestFor: 'Indonesian street vendors · warung · cafe',
    method: 'manual',
    fields: [
      { key: 'qrUrl', label: 'QRIS image URL', placeholder: 'https://...', type: 'url', required: true },
      { key: 'merchantName', label: 'Merchant name on QR', placeholder: 'Warung Bu Tini', type: 'text' },
    ],
    docUrl: null,
    setupSteps: ['Get a QRIS from your bank or e-wallet (free)', 'Upload the QR image to ImageKit or similar', 'Paste the image URL here', 'Customers scan to pay you directly'],
  },
  {
    id: 'bank',
    name: 'Bank Transfer',
    tagline: 'Direct deposit · works in every country',
    color: '#475569',
    logoUrl: null,
    countryFlags: '🌍',
    countryCount: 'Global',
    fees: '0%',
    bestFor: 'High-trust repeat customers · large orders',
    method: 'manual',
    bankPicker: true,   // tells the setup form to show a bank-picker dropdown
    fields: [
      { key: 'bankName', label: 'Bank', placeholder: 'Pick or type your bank', type: 'bank-picker', required: true },
      { key: 'accountNumber', label: 'Account number', placeholder: '1234567890', type: 'text', required: true },
      { key: 'accountName', label: 'Account holder name', placeholder: 'PT Street Local', type: 'text', required: true },
      { key: 'swift', label: 'SWIFT/BIC (international only)', placeholder: 'BNINIDJA', type: 'text' },
    ],
    docUrl: null,
    setupSteps: ['Enter your business bank account details', 'Customer copies the number from the order confirmation', 'They transfer from their banking app', 'You confirm receipt manually inside StreetLocal'],
  },
  {
    id: 'escrow',
    name: 'Escrow Hold',
    tagline: 'Funds held until customer confirms delivery',
    color: '#F59E0B',
    logoUrl: null,
    countryFlags: '🌍',
    countryCount: 'Wherever Stripe works',
    fees: 'Same as your Stripe rate · holds funds 1–30 days',
    bestFor: 'High-value products · new customers · marketplaces',
    method: 'requires-stripe',
    fields: [
      { key: 'holdDays', label: 'Hold period (days)', placeholder: '7', type: 'number' },
    ],
    docUrl: 'https://stripe.com/docs/connect/manual-payouts',
    setupSteps: ['Connect Stripe first', 'Choose hold duration (1–30 days)', 'Customer pays → Stripe holds → released to you after period or on confirmation'],
    comingSoon: true,
  },
]

export const ID_BANKS = [
  { code: 'BCA', name: 'BCA', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Bank_Central_Asia.svg/240px-Bank_Central_Asia.svg.png' },
  { code: 'MANDIRI', name: 'Bank Mandiri', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Bank_Mandiri_logo_2016.svg/320px-Bank_Mandiri_logo_2016.svg.png' },
  { code: 'BNI', name: 'BNI', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/BNI_logo.svg/200px-BNI_logo.svg.png' },
  { code: 'BRI', name: 'BRI', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/BANK_BRI_logo.svg/240px-BANK_BRI_logo.svg.png' },
  { code: 'PERMATA', name: 'Permata', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Permata_Bank_logo.svg/240px-Permata_Bank_logo.svg.png' },
  { code: 'CIMB', name: 'CIMB Niaga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/CIMB_Niaga_logo.svg/240px-CIMB_Niaga_logo.svg.png' },
  { code: 'DANAMON', name: 'Danamon', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Logo_Bank_Danamon.svg/240px-Logo_Bank_Danamon.svg.png' },
  { code: 'OTHER', name: 'Other / International', logo: null },
]

