export const ALL_BIOS = [
  // Humorous / relatable
  `I put the "pro" in procrastinate, but somehow still get things done at the very last second. Living life on deadlines, chaos, and a questionable amount of confidence that everything will magically work out.`,
  `Running on caffeine, zero sleep, and decisions I'll probably regret later. Somehow still functioning like a semi-responsible adult, but honestly just guessing my way through life one chaotic day at a time.`,
  `Not lazy, just highly committed to doing nothing until it becomes absolutely necessary. Then suddenly I unlock elite productivity like it's a hidden skill no one knew I had.`,
  `I'm not weird, I'm just a rare personality type that people don't fully understand. Either you get my vibe or you question my existence, and honestly both reactions are valid.`,
  `Life is a mess, but at least I know how to laugh through it. If everything is falling apart, I might as well enjoy the chaos and pretend it's all part of a bigger plan.`,
  `I came, I saw, I made things slightly more awkward than necessary. It's not intentional, it's just a natural talent I seem to have developed over time.`,
  `Fluent in sarcasm, overthinking, and making jokes at the worst possible moments. If timing was a skill, I'd still somehow manage to miss it completely.`,
  `Mentally somewhere peaceful and successful, physically here dealing with reality. It's a constant battle between what I want and what is actually happening.`,
  `I don't rise and shine, I wake up and question everything. Then I grab coffee and pretend I have my life together for the rest of the day.`,
  `Just chaos, but somehow still aesthetically pleasing. I don't know how it works either, but I'm not asking questions as long as it looks good.`,
  `I'm the reason group chats suddenly go silent or completely off track. There's no in-between, just confusion and entertainment mixed together.`,
  `Too glam to give a damn, but also too tired to actually do anything about it. It's a very confusing balance of confidence and exhaustion.`,
  `My hobbies include overthinking every situation and rewarding myself with snacks afterward. It's not productive, but it's consistent.`,
  `Professional overthinker with a master's degree in making simple things complicated. If there's a way to stress about it, I've already thought of it.`,
  `I act like I'm fine, but honestly I just need sleep, food, and a break from responsibilities. Until then, I'll keep pretending everything is under control.`,
  `If stress burned calories, I'd be in the best shape of my life right now. Unfortunately, it just gives me headaches and more things to worry about.`,
  `Half human, half confusion. Most of the time I'm just trying to figure out what's going on and hoping no one notices.`,
  `I'm not late, I just arrive exactly when I mean to. Time is more of a suggestion than a rule in my daily life.`,
  `My life feels like a deleted scene that somehow made it into the final version. It doesn't always make sense, but it's definitely interesting.`,
  `Confidence level depends on lighting, mood, and how much sleep I got. It's a fragile system, but it works most of the time.`,
  `I don't chase people, I trip over my own expectations and hope things fall into place. Surprisingly, it works more often than it should.`,
  `I'm on a seafood diet. I see food, I eat it, and then I regret nothing. Life is too short to say no to good food.`,
  `Plot twist: I have absolutely no idea what I'm doing, but I'm doing it with confidence. Sometimes that's all you really need.`,
  `Just vibing through life with questionable decisions and surprisingly decent outcomes. I don't question it, I just go with it.`,
  `Reality called, but I declined because I wasn't ready for that conversation. Maybe I'll deal with it later, maybe not.`,
  `I don't need therapy, I need money, food, and maybe a vacation. Until then, humor is my main coping mechanism.`,
  `My personality changes depending on how much sleep I got. Well-rested me and tired me are basically two completely different people.`,
  `Living proof that chaos and functionality can exist in the same person. It doesn't make sense, but somehow it works.`,
  `I laugh at my own jokes because I fully support myself. If no one else finds it funny, that's their problem.`,
  `Slightly unhinged but still socially acceptable most of the time. It's all about balance and knowing when to tone it down.`,
  `I'm not arguing, I'm just passionately explaining why I'm right. There's a difference, even if no one else sees it.`,
  `Brain loading… please wait. Sometimes it takes a while, but eventually I come up with something that makes sense.`,
  `I make bad decisions look like part of a bigger plan. Confidence really does make everything seem more intentional.`,
  `Life's too short to be normal, so I stopped trying. Now I just embrace whatever this is and hope for the best.`,
  `Currently under construction, but honestly I've been like this for a while. Growth takes time, and I'm taking my time.`,
  `I'm 90% sarcasm and 10% trying to function like a normal person. It's not easy, but I manage.`,
  `Not everyone likes me, and that's okay. I'm not for everyone, and honestly, everyone isn't for me either.`,
  `I'm not extra, you're just not used to this level of personality. It's a lot to handle, I understand.`,
  `My vibe changes depending on the music I'm listening to. One minute calm, next minute ready to start a whole new life.`,
  `I woke up like this… tired, confused, and already thinking about going back to sleep. It's a daily routine at this point.`,
  `Warning: I may randomly start talking about things that make no sense. Just go with it, it's part of the experience.`,
  `I don't sweat, I sparkle under pressure. Or at least that's what I tell myself to feel better about stressful situations.`,
  `My life is basically a comedy with no clear direction. I'm just here to see how it all plays out.`,
  `I'm not ignoring you, I'm just prioritizing my peace and maybe some snacks. It's nothing personal.`,
  `Living rent-free in my own thoughts, and honestly it's getting crowded in here. Too many ideas, not enough action.`,
  `I'm cool until something minor goes wrong, then suddenly everything is a problem. It escalates quickly.`,
  `Too tired to function properly but too awake to actually rest. Stuck in a constant state of confusion and low energy.`,
  `I didn't choose the chaos, the chaos chose me. At this point, I've just accepted it as part of my personality.`,
  `Keep rolling your eyes, maybe you'll eventually find something useful up there. Until then, I'll keep being entertaining.`,
  `Just here to confuse people, make questionable choices, and somehow enjoy life anyway. It's not perfect, but it's definitely interesting.`,

  // Genuine / inspirational
  `Living life with purpose, passion, and a little bit of chaos. I believe in growth, kindness, and chasing dreams no matter how far they seem.`,
  `Just a soul navigating through life, learning from every experience and growing stronger with every challenge. I value honesty, peace, and meaningful connections.`,
  `Building a life I don't need a vacation from. Focused on goals, driven by passion, and grounded in gratitude. Small steps every day lead to big results.`,
  `Not perfect, just real. Learning, evolving, and embracing every chapter of life. I believe in staying true to myself and trusting the process.`,
  `Chasing dreams and catching lessons along the way. I believe in hard work, self-growth, and staying positive even when life gets tough.`,
  `A simple person with big dreams. Focused on becoming better, not bitter. I believe in kindness, patience, and trusting that everything happens for a reason.`,
  `Living quietly, dreaming loudly. I prefer actions over words and progress over perfection. Always working on myself while enjoying the journey.`,
  `Just someone trying to make life meaningful. I believe in growth, good energy, and surrounding myself with people who inspire and uplift me.`,
  `Strong mind, soft heart, and a fearless spirit. I believe in staying kind in a world that isn't always kind, and pushing forward no matter what.`,
  `Creating my own path and writing my own story. I believe in independence, growth, and embracing change as a necessary part of becoming who I'm meant to be.`,
  `Living in the moment while building for the future. I believe in balance, self-discipline, and staying focused on what truly matters in life.`,
  `Focused on progress, not perfection. Every day is a chance to learn something new, grow stronger, and move one step closer to my goals.`,
  `Calm on the outside, driven on the inside. I believe in working hard in silence and letting success speak for itself in the end.`,
  `Just a dreamer with a plan. I believe in turning ideas into action and staying consistent no matter how slow the progress may seem.`,
  `Living with intention and purpose. I believe every decision shapes the future, so I choose growth, positivity, and resilience every single day.`,
  `Learning to enjoy the journey, not just the destination. Life is full of lessons, and I'm here for all of them, good and bad.`,
  `Real, raw, and always evolving. I believe in embracing change and becoming stronger through every experience life throws my way.`,
  `Quietly building something meaningful. I believe in patience, consistency, and trusting that hard work always pays off eventually.`,
  `Just a person trying to leave things better than I found them. I believe in kindness, respect, and making a positive impact in small ways.`,
  `Focused, determined, and always growing. I believe in myself, my journey, and the power of never giving up no matter what.`,
  `Living simply but dreaming big. I believe happiness comes from within and that growth is a lifelong journey worth embracing every day.`,
  `Driven by purpose, not pressure. I believe in creating a life that feels right, not just looks right to others around me.`,
  `Just navigating life one step at a time. I believe in patience, growth, and trusting the timing of everything as it unfolds.`,
  `A mix of ambition and calm. I believe in staying grounded while reaching for the stars and never losing myself in the process.`,
  `Building strength through challenges. I believe every obstacle is an opportunity to grow and become a better version of myself.`,
  `Living authentically and unapologetically. I believe in being true to who I am and not conforming to expectations that don't align with me.`,
  `Focused on becoming, not proving. I believe in growth, self-respect, and letting actions speak louder than words ever could.`,
  `Just someone who believes in possibilities. I believe anything can change with the right mindset and consistent effort over time.`,
  `Learning, growing, evolving. I believe life is about progress and becoming better than I was yesterday, one day at a time.`,
  `Living life on my own terms. I believe in freedom, self-growth, and creating a life that reflects who I truly am inside.`,
  `Calm energy with a strong mindset. I believe in staying peaceful while working hard toward everything I want in life.`,
  `Focused on building a future I'm proud of. I believe in discipline, patience, and staying committed to my goals no matter what.`,
  `Just a thinker and a dreamer. I believe in deep conversations, meaningful connections, and living with intention every day.`,
  `Growing through what I go through. I believe every experience shapes me into someone stronger and wiser than before.`,
  `Simple, driven, and real. I believe in staying grounded and never forgetting where I started or who I want to become.`,
  `Building quietly, achieving loudly. I believe success is best when it speaks for itself without needing validation from others.`,
  `Living for the moments that matter. I believe in making memories, staying present, and appreciating life as it is right now.`,
  `Focused on peace and progress. I believe in protecting my energy and working toward a better future every single day.`,
  `Just someone who refuses to give up. I believe persistence is the key to achieving anything truly worthwhile in life.`,
  `Balanced between dreams and reality. I believe in staying practical while still aiming high and never settling for less.`,
  `Learning to trust myself more each day. I believe self-confidence is built through action and consistency over time.`,
  `Living with gratitude and ambition. I believe appreciating the present while building the future is the key to real happiness.`,
  `Strong alone, unstoppable together. I believe in connection, support, and growing alongside the right people in life.`,
  `Just a soul with endless goals. I believe life is too short to not go after what I truly want with everything I have.`,
  `Quiet but powerful. I believe strength doesn't always need to be loud to be real or to make a lasting impact.`,
  `Focused on what I can control. I believe in letting go of what I can't and moving forward with clarity and purpose.`,
  `Living, learning, and leveling up. I believe in constant growth and never settling for less than I deserve in life.`,
  `Just someone chasing a better version of myself. I believe improvement is a lifelong commitment worth making every day.`,
  `Calm, collected, and consistent. I believe success comes from discipline and patience applied steadily over time.`,
  `Becoming who I'm meant to be, one day at a time. I believe everything is a process, and I'm trusting mine fully.`,

  // Silent grind / discipline
  `Moving in silence while building something meaningful behind the scenes. Focused on discipline, growth, and becoming someone my past version would admire.`,
  `Calm mindset, strong vision, and zero need for validation from anyone. I trust my journey, respect my pace, and keep moving forward no matter how slow it looks.`,
  `Not here to impress people who don't matter. I'm here to improve myself every single day and build a life that feels right, not one that just looks good from a distance.`,
  `Built from lessons, shaped by pressure, and driven by purpose. Every setback taught me something valuable, and every step forward proves I'm stronger than what tried to stop me.`,
  `Quietly leveling up while others focus on noise. Consistency is my advantage, and patience is my strategy as I build something that will last.`,
  `Focused on becoming better instead of proving anything to anyone. Growth is personal, and I move at my own pace without comparing my journey to others.`,
  `I don't compete with people, I create my own path and stay focused on it. Comparison is distraction, and I don't have time to lose focus on what really matters.`,
  `Discipline over motivation, because motivation fades but discipline stays. I show up even when I don't feel like it, and that's what separates progress from excuses.`,
  `Progress is my only competition. I'm always trying to outgrow who I was yesterday and become more focused, more patient, and more consistent over time.`,
  `I move differently because I think differently. I don't follow crowds, I follow purpose, and that's what keeps me moving forward with clarity.`,
  `Less talk, more action. I let results speak louder than promises, because words don't mean much without effort behind them.`,
  `Energy unmatched, mindset unshaken, and focus locked in. I don't let distractions slow me down when I know exactly what I'm working toward.`,
  `I adapt, I learn, and I keep moving forward no matter what happens. Stopping is never an option when growth is the goal and the standard is high.`,
  `Everything I want is already in progress. I just need to stay patient, consistent, and focused while it all comes together in its own time.`,
  `Focused so deeply on my goals that I forgot to doubt myself. Confidence grows when you stay committed to your path and trust the process.`,
  `Growth is part of my daily routine now. I don't wait for change, I create it through small consistent actions that add up over time.`,
  `Success is built quietly, far away from distractions and noise. What people don't see is what matters the most and what drives me.`,
  `No shortcuts, just discipline, patience, and effort repeated daily. That's how real progress is made and how lasting results are earned.`,
  `Becoming better every day, even if it's just a small step forward. Progress is progress no matter how slow it feels in the moment.`,
  `Mindset locked in and focused on the bigger picture. Temporary comfort doesn't distract me from the long-term goals I'm working toward.`,
  `Pressure made me stronger instead of breaking me. I learned how to handle challenges and turn them into fuel for growth and clarity.`,
  `I create my own opportunities instead of waiting for them. Action always beats waiting and hoping that things will somehow fall into place.`,
  `Vision clear, distractions ignored, and goals always in mind. I know exactly what I'm working toward and why it matters to me.`,
  `Working now so I can live freely later. Sacrifice today creates the freedom tomorrow that most people only talk about wanting.`,
  `Staying solid even when things around me feel unstable. Strength comes from staying grounded and focused through every storm that comes.`,
  `Growth requires discomfort, and I've learned to embrace it fully. Nothing great comes from staying comfortable and avoiding the hard parts.`,
  `I don't follow trends, I follow what works for me. That's how I stay consistent, focused, and true to my own path.`,
  `Different mindset, different life. The way you think shapes everything around you and determines what you're capable of achieving.`,
  `Self-made mentality with no excuses attached. I take full responsibility for where I am and where I'm going from here.`,
  `Always prepared for what's next, even when it's uncertain. Growth comes from stepping into the unknown with confidence and a clear head.`,
]

export function shuffleBios() {
  const a = [...ALL_BIOS]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}
